#if !LITE_BUILD
import Foundation
import LiveWallpaperProWPE

extension WPEShaderTranspiler {
    // MARK: - Render

    static func renderMSL(
        shaderName: String,
        uniforms: [WPEUniformDecl],
        totalUniformSlots: Int,
        samplers: [WPESamplerDecl],
        /// Slots to declare. Sized per shader by `textureSlotCount(for:)`; the dispatcher
        /// binds exactly this many, so the two must come from the same value.
        textureSlotCount: Int,
        varyings: [WPEVaryingDecl],
        helpers: String,
        mainBody: String,
        mutableGlobals: [ProgramScopeMutableDecl] = [],
        comboValues: [String: Int] = [:],
        premultipliedInputSlots: Set<Int> = [],
        premultipliedOutput: Bool = false,
        waterOptimizationsEnabled: Bool = Self.waterOptimizationsEnabled
    ) -> String {
        // Stock Pulse blends authored colour values; the host's colour targets are linear.
        // Its mask/noise inputs remain data, and alpha stays outside the transfer function.
        let encodedPulse = shaderName.lowercased() == "effects/pulse"
            && premultipliedInputSlots == [0] && premultipliedOutput
        let warningCleanHelpers = neutralizeMetalStdlibMacroRedefinitions(helpers)
        let waterMain = waterOptimizationsEnabled
            ? specializingWaterWavePower(mainBody, uniforms: uniforms, helpers: helpers) : mainBody
        let flow = waterOptimizationsEnabled
            ? waterflowEndpointRewrite(waterMain, helpers: helpers, premultiplied: premultipliedInputSlots.contains(0))
            : (main: waterMain, helper: "")
        let warningCleanMainBody = neutralizeMetalStdlibMacroRedefinitions(flow.main)
        var out: [String] = [
            "#include <metal_stdlib>",
            "using namespace metal;",
            "",
            "// Generated by WPEShaderTranspiler from \(shaderName).",
            ""
        ]

        if waterMain != mainBody {
            // The exponent is a live uniform, not a baked material value. Preserve
            // the authored sign multiply and time calculation, including zeroes.
            out.append("inline float wpe_unit_exponent_power(float magnitude, float exponent) {")
            out.append("    if (exponent == 1.0) { return magnitude; }")
            out.append("    return pow(magnitude, exponent);")
            out.append("}")
        }
        out.append("struct WPEStageIn {")
        out.append("    float4 position [[position]];")
        out.append("    float2 uv;")
        out.append("};")
        out.append("")

        if !uniforms.isEmpty {
            // Size to this shader's own slot count, not `uniformSlotMaximum`: the host binds exactly
            // `totalSlots × 16` bytes, and Metal validation rejects a buffer shorter than the struct.
            out.append("struct WPEUniforms {")
            out.append("    float4 vals[\(max(totalUniformSlots, 1))];")
            out.append("};")
            out.append("")
        }

        out.append("[[maybe_unused]] constexpr sampler linearSampler(address::clamp_to_edge, filter::linear);")
        out.append("[[maybe_unused]] constexpr sampler repeatSampler(address::repeat, filter::linear);")
        out.append("inline float min(int lhs, float rhs) { return metal::min(float(lhs), rhs); }")
        out.append("inline float min(float lhs, int rhs) { return metal::min(lhs, float(rhs)); }")
        out.append("inline float max(int lhs, float rhs) { return metal::max(float(lhs), rhs); }")
        out.append("inline float max(float lhs, int rhs) { return metal::max(lhs, float(rhs)); }")
        out.append("inline float clamp(int value, float lower, float upper) { return metal::clamp(float(value), lower, upper); }")
        out.append("inline float clamp(float value, int lower, float upper) { return metal::clamp(value, float(lower), upper); }")
        out.append("inline float clamp(float value, float lower, int upper) { return metal::clamp(value, lower, float(upper)); }")
        out.append("inline float clamp(int value, int lower, float upper) { return metal::clamp(float(value), float(lower), upper); }")
        out.append("inline float clamp(int value, float lower, int upper) { return metal::clamp(float(value), lower, float(upper)); }")
        out.append("inline float clamp(float value, int lower, int upper) { return metal::clamp(value, float(lower), float(upper)); }")
        out.append(Self.glslMathPrelude)
        if !premultipliedInputSlots.isEmpty {
            out.append("inline float4 wpe_unpremultiply_sample(float4 color) {")
            out.append("    float a = color.a;")
            out.append("    color.rgb = a > 0.00001 ? color.rgb / a : float3(0.0);")
            if encodedPulse {
                out.append("    float3 rgb = max(color.rgb, float3(0.0));")
                out.append("    color.rgb = select(1.055 * pow(rgb, float3(1.0 / 2.4)) - 0.055, rgb * 12.92, rgb <= 0.0031308);")
            }
            out.append("    return color;")
            out.append("}")
        }
        if premultipliedOutput {
            out.append("inline float4 wpe_premultiply_output(float4 color) {")
            out.append("    float a = metal::clamp(color.a, 0.0, 1.0);")
            if encodedPulse {
                out.append("    float3 rgb = max(color.rgb, float3(0.0));")
                out.append("    color.rgb = select(pow((rgb + 0.055) / 1.055, float3(2.4)), rgb / 12.92, rgb <= 0.04045);")
            }
            out.append("    return float4(color.rgb * a, a);")
            out.append("}")
        }
        appendCompatibilityPrelude(
            to: &out,
            helpers: warningCleanHelpers,
            comboValues: comboValues
        )
        if !flow.helper.isEmpty { out.append(flow.helper) }
        out.append("")

        if !warningCleanHelpers.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            out.append(warningCleanHelpers)
            out.append("")
        }

        // Join parameters with commas: `textureSlotCount` 0 would leave a dangling comma on the last fixed parameter.
        var parameters = ["    WPEStageIn in [[stage_in]]"]
        if !uniforms.isEmpty {
            parameters.append("    constant WPEUniforms& u [[buffer(0)]]")
        }
        for slot in 0..<textureSlotCount {
            parameters.append("    texture2d<float> tex\(slot) [[texture(\(slot))]]")
        }
        // Per-slot samplers: address/filter come from TEXI flags at dispatch, not the old clamp-every-content-texture heuristic.
        for slot in 0..<textureSlotCount {
            parameters.append("    sampler wpeSampler\(slot) [[sampler(\(slot))]]")
        }
        let signature = [
            "fragment float4 wpe_translated_fragment(",
            parameters.joined(separator: ",\n"),
            ") {"
        ]
        out.append(signature.joined(separator: "\n"))

        // Alias `g_TextureN` to texN (the real slot); enumeration order would map `g_Texture2` to tex0.
        for (index, sampler) in samplers.enumerated() {
            let slot = Self.textureSlot(for: sampler.name) ?? index
            out.append("    [[maybe_unused]] auto \(sampler.name) = tex\(slot);")
        }
        out.append(contentsOf: Self.uniformDeclarationLines(uniforms))

        let uniformNames = Set(uniforms.map(\.name))
        let varyingReconstruction = autoSwayVaryingReconstructionLines(
            varyings: varyings,
            availableUniforms: uniformNames,
            comboValues: comboValues
        ) + bokehBlurVaryingReconstructionLines(
            varyings: varyings,
            availableUniforms: uniformNames,
            comboValues: comboValues
        ) + frameBuilderVaryingReconstructionLines(
            varyings: varyings,
            availableUniforms: uniformNames,
            comboValues: comboValues
        )
        // A non-`v_TexCoord` varying that falls back to a 0→1 UV ramp renders wrong; emit a diagnostic marker instead of staying silent.
        let uvFallbackInitializers: Set<String> = [
            "in.uv", "in.uv.x", "float4(in.uv, in.uv)", "float3(in.uv, 0.0)",
        ]
        // Audio varyings fall back to constant 0, not a UV ramp, so a missing spectrum uniform stops the effect rather than rendering wrong.
        let flatFallbackVaryings: Set<String> = ["v_AudioPulse", "v_AudioShift"]
        for varying in varyings {
            if varying.name == "uv" { continue }
            let initializer = varyingInitializer(
                for: varying,
                shaderName: shaderName,
                availableUniforms: uniformNames,
                comboValues: comboValues
            )
            let isUVFallback = uvFallbackInitializers.contains(initializer)
            if varying.name != "v_TexCoord",
               isUVFallback || (initializer == "0.0" && flatFallbackVaryings.contains(varying.name)),
               // A reconstruction may assign the whole varying or only components
               // (`v_Transform.x = …`), so match the assignment target, not just ` name = `.
               !varyingReconstruction.contains(where: {
                   $0.contains(" \(varying.name) = ") || $0.contains(" \(varying.name).")
               }),
               warningCleanMainBody.range(of: "\\b\(NSRegularExpression.escapedPattern(for: varying.name))\\b", options: .regularExpression) != nil {
                let fallback = isUVFallback ? "screen-UV" : "constant-zero"
                out.append("    // WPE-DIAGNOSTIC: varying '\(varying.name)' has no reconstruction rule and fell back to a \(fallback) default; this likely renders incorrectly.")
            }
            if let arrayLength = varying.arrayLength {
                let initializers = texCoordBoxFilterInitializers(varying: varying, availableUniforms: uniformNames)
                    ?? Array(repeating: initializer, count: arrayLength)
                out.append("    [[maybe_unused]] \(varying.metalType) \(varying.name)[\(arrayLength)] = { \(initializers.joined(separator: ", ")) };")
            } else if let arrayDimension = varying.arrayDimension {
                // Symbolic `#define`-sized arrays cannot expand a literal initializer; zero-init and let reconstructions fill slots.
                out.append("    [[maybe_unused]] \(varying.metalType) \(varying.name)[\(arrayDimension)] = {};")
                out.append(
                    contentsOf: symbolicArrayReconstructionLines(
                        for: varying,
                        availableUniforms: uniformNames,
                        comboValues: comboValues
                    )
                )
            } else {
                out.append("    [[maybe_unused]] \(varying.metalType) \(varying.name) = \(initializer);")
            }
        }

        for declaration in mutableGlobals {
            out.append("    [[maybe_unused]] \(declaration.metalType) \(declaration.name) = \(declaration.initializer);")
        }

        out.append(contentsOf: varyingReconstruction)

        out.append("    {")
        out.append(warningCleanMainBody)
        out.append("    }")
        out.append("}")
        return routingGLSLMixCalls(
            in: out.joined(separator: "\n"),
            authoredHelpers: warningCleanHelpers,
            authoredMain: warningCleanMainBody
        )
    }

    /// The identity form (`#define mix mix`) can only come from authored source now that the prelude's
    /// `#define lerp mix` keeps its own name; it does not change what `mix` means, so it does not block the rewrite.
    private static func overridesWaterIntrinsics(_ source: String, names: Set<String>) -> Bool {
        let joined = source.replacingOccurrences(of: "\\\r\n", with: "")
            .replacingOccurrences(of: "\\\n", with: "")
        return maskComments(joined).components(separatedBy: "\n").contains { line in
            guard let name = defineMacroName(in: line), names.contains(name) else { return false }
            let identity = line.range(of: #"^\s*#\s*define\s+mix\s+mix\s*$"#, options: .regularExpression) != nil
            return !(name == "mix" && identity)
        }
    }

    /// Narrow scalar expression rewrite; custom pow implementations keep their
    /// semantics. No shader-name routing or time/phase specialization is involved.
    private static func specializingWaterWavePower(
        _ body: String, uniforms: [WPEUniformDecl], helpers: String
    ) -> String {
        let code = maskComments(body)
        // The authored wave main has no nested scopes. Unknown control flow and
        // local exponent declarations retain the original expression unchanged.
        guard !code.contains("{"), !code.contains("}"),
              code.range(of: #"\b(?:float[234]?|half[234]?|int[234]?|uint[234]?|auto)\s+[^;]*\bg_Exponent2?\b"#, options: .regularExpression) == nil,
              !overridesWaterIntrinsics(helpers + "\n" + body, names: ["pow"]),
              !parseHelperFunctions(in: helpers).contains(where: { $0.name == "pow" }),
              !helpers.contains("wpe_unit_exponent_power"), !body.contains("wpe_unit_exponent_power") else { return body }
        var result = body
        for (value, exponent) in [("val1", "g_Exponent"), ("val2", "g_Exponent2")] {
            guard uniforms.contains(where: { $0.name == exponent && $0.type == "float" && $0.arrayLength == nil }),
                  maskComments(body).range(of: #"\bfloat\s+"# + value + #"\s*=\s*sin\s*\("#, options: .regularExpression) != nil else { continue }
            let pattern = #"(?<![\w:])pow\s*\(\s*abs\s*\(\s*"# + value + #"\s*\)\s*,\s*"# + exponent + #"\s*\)"#
            guard let regex = try? NSRegularExpression(pattern: pattern) else { continue }
            let masked = maskComments(result)
            let declarationPattern = #"\b(?:float[234]?|half[234]?|int[234]?|auto)\s+"# + value + #"\b"#
            guard let declarations = try? NSRegularExpression(pattern: declarationPattern),
                  declarations.numberOfMatches(in: masked, range: NSRange(masked.startIndex..., in: masked)) == 1 else { continue }
            for match in regex.matches(in: masked, range: NSRange(masked.startIndex..., in: masked)).reversed() {
                guard let matchRange = Range(match.range, in: masked) else { continue }
                // maskComments preserves Character count, including Unicode comments.
                let lower = result.index(result.startIndex, offsetBy: masked.distance(from: masked.startIndex, to: matchRange.lowerBound))
                let upper = result.index(lower, offsetBy: masked.distance(from: matchRange.lowerBound, to: matchRange.upperBound))
                result.replaceSubrange(lower ..< upper, with: "wpe_unit_exponent_power(abs(\(value)), \(exponent))")
            }
        }
        return result
    }

    /// Match the authored four-sample blend, not an effect name.
    /// Single-mip FBOs may use explicit lod 0 in divergent branches; mipmapped sources keep implicit gradients.
    private static func waterflowEndpointRewrite(
        _ body: String, helpers: String, premultiplied: Bool
    ) -> (main: String, helper: String) {
        let marker = "wpe_flow_endpoint_color"
        guard !helpers.contains(marker), !body.contains(marker),
              !overridesWaterIntrinsics(helpers + "\n" + body, names: ["mix", "wpe_smoothstep", "wpe_unpremultiply_sample"]),
              !parseHelperFunctions(in: helpers).contains(where: { ["mix", "wpe_smoothstep", "wpe_unpremultiply_sample"].contains($0.name) }),
              let start = body.range(of: "[[maybe_unused]] float4 flowAlbedo ="),
              let end = body.range(of: "flowAlbedo = mix(flowAlbedo, flowAlbedo2, wpe_smoothstep(0.2, 0.8, flowPhase));"),
              start.lowerBound < end.upperBound else { return (body, "") }
        func sample(_ uv: String, explicit: Bool = false, arguments: String = "g_Texture0.sample(wpeSampler0, ") -> String {
            let read = arguments + uv + (explicit ? ", level(0.0))" : ")")
            return premultiplied ? "wpe_unpremultiply_sample(\(read))" : read
        }
        let expected = """
        [[maybe_unused]] float4 flowAlbedo = mix(\(sample("v_TexCoord.xy + flowUVOffset.xy")),
            \(sample("v_TexCoord.xy + flowUVOffset.zw")), v_Blend.x);
        [[maybe_unused]] float4 flowAlbedo2 = mix(\(sample("v_TexCoord.xy + flowUVOffset2.xy")),
            \(sample("v_TexCoord.xy + flowUVOffset2.zw")), v_Blend.y);
        flowAlbedo = mix(flowAlbedo, flowAlbedo2, wpe_smoothstep(0.2, 0.8, flowPhase));
        """
        let range = start.lowerBound ..< end.upperBound
        guard body[range].filter({ !$0.isWhitespace }) == expected.filter({ !$0.isWhitespace }),
              body.components(separatedBy: "flowAlbedo2").count == 3 else { return (body, "") }
        let uv = ["uv + offsets.xy", "uv + offsets.zw", "uv + offsets2.xy", "uv + offsets2.zw"]
        let implicit = uv.map { sample($0, arguments: "image.sample(state, ") }
        let explicit = uv.map { sample($0, explicit: true, arguments: "image.sample(state, ") }
        let code = """
        inline float4 \(marker)(texture2d<float> image, sampler state, float2 uv,
                                       float4 offsets, float4 offsets2, float2 blend, float phase) {
            float weight = wpe_smoothstep(0.2, 0.8, phase);
            if (image.get_num_mip_levels() > 1) {
                float4 first = mix(\(implicit[0]), \(implicit[1]), blend.x);
                float4 second = mix(\(implicit[2]), \(implicit[3]), blend.y);
                return mix(first, second, weight);
            } else {
                if (weight == 0.0) { return mix(\(explicit[0]), \(explicit[1]), blend.x); }
                if (weight == 1.0) { return mix(\(explicit[2]), \(explicit[3]), blend.y); }
                float4 first = mix(\(explicit[0]), \(explicit[1]), blend.x);
                float4 second = mix(\(explicit[2]), \(explicit[3]), blend.y);
                return mix(first, second, weight);
            }
        }
        """
        let replacement = "[[maybe_unused]] float4 flowAlbedo = \(marker)(g_Texture0, wpeSampler0, v_TexCoord.xy, flowUVOffset, flowUVOffset2, v_Blend, flowPhase);"
        return (body.replacingCharacters(in: range, with: replacement), code)
    }

    private static let metalStdlibMacroDefinitions: Set<String> = [
        "M_PI_F"
    ]

    private static func neutralizeMetalStdlibMacroRedefinitions(_ source: String) -> String {
        guard source.contains("#") else { return source }
        return source.components(separatedBy: "\n").map { line in
            guard let macroName = defineMacroName(in: line),
                  metalStdlibMacroDefinitions.contains(macroName) else {
                return line
            }
            return "// disabled duplicate Metal stdlib macro definition: \(macroName)"
        }.joined(separator: "\n")
    }

    private static func defineMacroName(in line: String) -> String? {
        var trimmed = line.trimmingCharacters(in: .whitespaces)
        guard trimmed.first == "#" else { return nil }
        trimmed.removeFirst()

        let directive = trimmed.trimmingCharacters(in: .whitespaces)
        guard directive.hasPrefix("define") else { return nil }

        let afterDirective = directive.dropFirst("define".count)
        guard afterDirective.first?.isWhitespace == true else { return nil }
        let afterWhitespace = afterDirective.drop(while: { $0.isWhitespace })
        guard let first = afterWhitespace.first, isIdentifierStart(first) else { return nil }

        var name = ""
        for ch in afterWhitespace {
            guard isIdentifierCharacter(ch) else { break }
            name.append(ch)
        }
        return name
    }

    private static func appendCompatibilityPrelude(
        to out: inout [String],
        helpers: String,
        comboValues: [String: Int]
    ) {
        let existingFunctionNames = Set(parseHelperFunctions(in: maskComments(helpers)).map(\.name))

        if !existingFunctionNames.contains("mod") {
            out.append("inline float mod(float x, float y) { return x - y * floor(x / y); }")
            out.append("inline float mod(float x, int y) { return mod(x, float(y)); }")
            out.append("inline float2 mod(float2 x, float2 y) { return x - y * floor(x / y); }")
            out.append("inline float2 mod(float2 x, float y) { return mod(x, float2(y)); }")
            out.append("inline float2 mod(float2 x, int y) { return mod(x, float(y)); }")
            out.append("inline float3 mod(float3 x, float3 y) { return x - y * floor(x / y); }")
            out.append("inline float3 mod(float3 x, float y) { return mod(x, float3(y)); }")
            out.append("inline float3 mod(float3 x, int y) { return mod(x, float(y)); }")
            out.append("inline float4 mod(float4 x, float4 y) { return x - y * floor(x / y); }")
            out.append("inline float4 mod(float4 x, float y) { return mod(x, float4(y)); }")
            out.append("inline float4 mod(float4 x, int y) { return mod(x, float(y)); }")
        }

        if !existingFunctionNames.contains("greyscale") {
            out.append("inline float greyscale(float3 c) { return dot(c, float3(0.299, 0.587, 0.114)); }")
            out.append("inline float greyscale(float4 c) { return greyscale(c.rgb); }")
        }

        if !existingFunctionNames.contains("rgb2hsv") {
            out.append(
                """
                inline float3 rgb2hsv(float3 c) {
                    float4 K = float4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);
                    float4 p = mix(float4(c.bg, K.wz), float4(c.gb, K.xy), step(c.b, c.g));
                    float4 q = mix(float4(p.xyw, c.r), float4(c.r, p.yzx), step(p.x, c.r));
                    float d = q.x - min(q.w, q.y);
                    float e = 1.0e-10;
                    return float3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);
                }
                """
            )
        }

        if !existingFunctionNames.contains("hsv2rgb") {
            out.append(
                """
                inline float3 hsv2rgb(float3 c) {
                    float4 K = float4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);
                    float3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
                    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
                }
                """
            )
        }

        if !existingFunctionNames.contains("DecompressNormal") {
            let texture1Format = comboValues["TEX1FORMAT"]
                ?? WPEOfficialTextureFormatABI.rgba8888
            let assignmentSwizzle: String
            let packedChannels: String
            let packedBias: String
            if WPEOfficialTextureFormatABI.isCompressedNormalFormat(texture1Format) {
                assignmentSwizzle = ".yx"
                packedChannels = "packed.yw"
                packedBias = "float2(0.965, 1.0)"
            } else if texture1Format == WPEOfficialTextureFormatABI.rg88 {
                assignmentSwizzle = ""
                packedChannels = "packed.rg"
                packedBias = "float2(1.0)"
            } else {
                assignmentSwizzle = ""
                packedChannels = "packed.wy"
                packedBias = "float2(1.0)"
            }
            out.append(
                """
                inline float3 DecompressNormal(float4 packed) {
                    float2 nxy;
                    nxy\(assignmentSwizzle) = \(packedChannels) * 2.0 - \(packedBias);
                    float nz = sqrt(max(0.0, 1.0 - dot(nxy, nxy)));
                    return float3(nxy, nz);
                }
                """
            )
            out.append("inline float3 DecompressNormal(float3 packed) { return DecompressNormal(float4(packed, 0.0)); }")
        }

        out.append(
            """
            inline float wpe_safe_ratio(float numerator, float denominator) {
                return abs(denominator) > 0.000001 ? numerator / denominator : 0.0;
            }
            inline float2 wpe_rotate_vec2(float2 v, float angle) {
                float c = cos(angle);
                float s = sin(angle);
                return float2(c * v.x - s * v.y, s * v.x + c * v.y);
            }
            inline float2 wpe_safe_normalize(float2 v) {
                float len = length(v);
                return len > 1e-8 ? v / len : float2(0.0, 1.0);
            }
            inline float2 wpe_scroll_vector(float scrollX, float scrollY, float time) {
                float2 scroll = float2(scrollX, scrollY);
                return sign(scroll) * pow(abs(scroll), float2(2.0)) * time;
            }
            inline float4 wpe_texcoord_with_resolution(float2 uv, float4 resolution) {
                float2 scale = float2(
                    wpe_safe_ratio(resolution.z, resolution.x),
                    wpe_safe_ratio(resolution.w, resolution.y)
                );
                return float4(uv, uv * scale);
            }
            inline float4 wpe_texcoord_mask(float2 uv, float4 resolution) {
                float2 scale = float2(
                    wpe_safe_ratio(resolution.z, resolution.x),
                    wpe_safe_ratio(resolution.w, resolution.y)
                );
                return float4(uv * scale, scale);
            }
            // swing.vert/twirl.vert v_TexCoord: .z = the layer aspect (swing reads
            // g_Texture0Resolution.x/.y, twirl .z/.w), .w = sin(t·speed + phase·2π)·amount —
            // the time-driven phase. Deliberately absent from the texCoordZWResolutionSlot
            // family table (.zw packs aspect+phase, not a scaled UV); the float4(in.uv, in.uv)
            // default fed screen position into both, freezing the animation into a position-dependent warp. Degenerate resolution falls back to aspect 1 (not 0), since both fragments divide by .z.
            inline float4 wpe_swing_texcoord(float2 uv, float2 resolution, float time, float speed, float phase, float amount) {
                float aspect = wpe_safe_ratio(resolution.x, resolution.y);
                return float4(uv, abs(aspect) > 0.000001 ? aspect : 1.0, sin(time * speed + phase * 6.28318530718) * amount);
            }
            inline float4 wpe_ripple_texcoord(float2 uv, float time, float animationSpeed, float scrollSpeed, float direction, float ratio, float scale, float4 texture0Resolution) {
                float animation = time * animationSpeed * animationSpeed;
                float2 scroll = wpe_rotate_vec2(float2(0.0, 1.0), direction) * scrollSpeed * scrollSpeed * time;
                float4 ripple = float4(uv + animation + scroll, uv * 1.333 - animation + scroll) * scale;
                ripple.xz *= wpe_safe_ratio(texture0Resolution.x, texture0Resolution.y);
                ripple.yw *= ratio;
                return ripple;
            }
            inline float2 wpe_iris_texcoord(float timeUniform, float speed, float phaseOffset, float rough, float noiseAmount, float2 scale) {
                float time = timeUniform * speed + phaseOffset;
                float lowDt = floor(time);
                float2 motion2 = sin(1.9 * (lowDt + float2(0.0, 1.0)));
                float4 motion4 = sin(2.5 * (lowDt + float4(0.0, 0.0, 1.0, 1.0)) + float4(1.0, 2.0, 1.0, 2.0));
                float2 moveStart = motion2.xx + motion4.xy;
                float2 moveEnd = motion2.yy + motion4.zw;
                float eased = wpe_smoothstep(1.0 - rough, 1.0, cos(fract(time) * 3.14159265359) * -0.5 + 0.5);
                float2 da = mix(moveStart, moveEnd, eased);
                da.x += sin(time) * noiseAmount;
                da.y += cos(time) * noiseAmount;
                return da * scale * 0.001;
            }
            inline float wpe_foliage_aspect(float4 texture0Resolution, float ratio) {
                float aspect = wpe_safe_ratio(texture0Resolution.z, texture0Resolution.w) * ratio;
                return abs(aspect) > 0.000001 ? aspect : 1.0;
            }
            inline float4 wpe_foliage_texcoord_noise(float2 uv, float noiseScale, float ratio, float direction, float4 texture0Resolution) {
                float aspect = wpe_foliage_aspect(texture0Resolution, ratio);
                return float4(uv * noiseScale, wpe_rotate_vec2(float2(1.0 / aspect, aspect), direction));
            }
            inline float3 wpe_foliage_params(float2 uv, float direction, float strength) {
                return float3(wpe_rotate_vec2(uv, direction), strength * strength * 0.005);
            }
            // filmgrain.vert's v_TexCoordNoise: two noise lookups scrolled by frac(time)
            // and tiled by g_NoiseScale (aspect-corrected on x). Distinct from the foliage
            // variant above — without it the varying fell back to raw uv, sampling the
            // 256² noise once across the whole frame (smooth blotches soft-light blended
            // over everything = a static "retro filter") instead of fine animated grain.
            inline float4 wpe_filmgrain_texcoord_noise(float2 uv, float time, float scale, float4 texture0Resolution) {
                float t = fract(time);
                float aspect = wpe_safe_ratio(texture0Resolution.z, texture0Resolution.w);
                float4 coords = float4((uv + t) * scale, (uv - t * 2.5) * scale * 0.52);
                return coords * float4(aspect, 1.0, aspect, 1.0);
            }
            inline float2 wpe_bounds_vector(float2 bounds) {
                return float2(bounds.x, 1.0 / max(bounds.y - bounds.x, 0.000001));
            }
            // pulse.vert's non-audio `v_Pulse`: a time-driven sine gated through
            // g_PulseThresholds, scaled by g_PulseAmount (0 at rest, pulses over time).
            // Without it the float varying defaulted to `in.uv.x` — a left-to-right
            // brightness/alpha ramp instead of a uniform full-screen pulse.
            inline float wpe_pulse_response(float time, float2 thresholds, float speed, float phase, float amount) {
                float wave = sin(time * speed + (phase - 0.25) * 6.28318530717958647692) * 0.5 + 0.5;
                return wpe_smoothstep(thresholds.x, thresholds.y, wave) * amount;
            }
            // Vertex-stage `v_AudioShift` (WPE common.h CreateAudioResponse): FFT bins in
            // [freqMin, freqMax] averaged, smoothstepped against g_AudioBounds, raised to
            // g_AudioPower, scaled by g_AudioMultiply. `mode` is the AUDIOPROCESSING combo
            // (1=left, 2=right, 3=both); returns 0 when silent, matching WPE. The fragment-only
            // transpile has no vertex stage, so without this the varying defaulted to `in.uv.x`, smearing the whole frame (chromatic aberration/hue_shift glitch even with no audio).
            inline float wpe_audio_response16(
                thread const float (&left)[16],
                thread const float (&right)[16],
                int mode, float freqMin, float freqMax,
                float2 bounds, float power, float multiply
            ) {
                int lo = clamp(int(freqMin), 0, 15);
                int hi = clamp(int(freqMax), 0, 15);
                float response = 0.0;
                for (int a = lo; a <= hi; ++a) {
                    if (mode == 2) { response += right[a]; }
                    else if (mode == 3) { response += left[a] + right[a]; }
                    else { response += left[a]; }
                }
                float denom = max(freqMax - freqMin + 1.0, 1.0);
                if (mode == 3) { denom *= 2.0; }
                response /= denom;
                response = wpe_smoothstep(bounds.x, bounds.y, response);
                return clamp(pow(response, power), 0.0, 1.0) * multiply;
            }
            inline float wpe_audio_oscilloscope_value(
                float left, float right, int index, int resolution,
                int equalize, float lrBalance, float freqBalanceUniform, float ampExponent
            ) {
                float leftBalance = equalize != 0 ? (1.0 - lrBalance) * 0.5 : 0.5;
                float rightBalance = equalize != 0 ? (lrBalance + 1.0) * 0.5 : 0.5;
                float normalizedFrequency = float(index) / max(float(resolution), 1.0);
                float freqBalance = 1.0;
                if (equalize != 0) {
                    float bassBalance = (1.0 - freqBalanceUniform) * (1.0 - normalizedFrequency);
                    float trebleBalance = freqBalanceUniform * normalizedFrequency;
                    freqBalance = mix(bassBalance, trebleBalance, normalizedFrequency) * 2.5;
                }
                float amplitude = left * leftBalance + right * rightBalance;
                return pow(max(freqBalance * (amplitude + amplitude), 0.0), ampExponent + 0.01);
            }
            inline float4 wpe_waterflow_cycles(float time, float speed) {
                float t = time * speed;
                float4 cycles = float4(fract(t), fract(t + 0.5), fract(0.25 + t), fract(0.25 + t + 0.5));
                return cycles - float4(0.5);
            }
            // Expose the shared phase expressions to CSE with wpe_waterflow_cycles.
            // Plain inline can leave this helper out of line in optimized AIR.
            __attribute__((always_inline)) inline float2 wpe_waterflow_blend(float time, float speed, float feather) {
                float t = time * speed;
                float bx = 2.0 * abs(fract(t) - 0.5);
                float bz = 2.0 * abs(fract(0.25 + t) - 0.5);
                float lo = 0.5 - feather, hi = 0.5 + feather;
                return float2(wpe_smoothstep(lo, hi, bx), wpe_smoothstep(lo, hi, bz));
            }
            inline float3x3 wpe_square_to_quad(float2 p0, float2 p1, float2 p2, float2 p3) {
                float dx0 = p0.x, dy0 = p0.y;
                float dx1 = p1.x, dy1 = p1.y;
                float dx2 = p3.x, dy2 = p3.y;
                float dx3 = p2.x, dy3 = p2.y;
                float diffx1 = dx1 - dx3;
                float diffy1 = dy1 - dy3;
                float diffx2 = dx2 - dx3;
                float diffy2 = dy2 - dy3;
                float det = diffx1 * diffy2 - diffx2 * diffy1;
                float sumx = dx0 - dx1 + dx3 - dx2;
                float sumy = dy0 - dy1 + dy3 - dy2;
                if (det == 0.0 || (sumx == 0.0 && sumy == 0.0)) {
                    return float3x3(
                        float3(dx1 - dx0, dy1 - dy0, 0.0),
                        float3(dx3 - dx1, dy3 - dy1, 0.0),
                        float3(dx0, dy0, 1.0)
                    );
                }
                float ovdet = 1.0 / det;
                float g = (sumx * diffy2 - diffx2 * sumy) * ovdet;
                float h = (diffx1 * sumy - sumx * diffy1) * ovdet;
                return float3x3(
                    float3(dx1 - dx0 + g * dx1, dy1 - dy0 + g * dy1, g),
                    float3(dx2 - dx0 + h * dx2, dy2 - dy0 + h * dy2, h),
                    float3(dx0, dy0, 1.0)
                );
            }
            inline float3x3 wpe_mat3_inverse(float3x3 m) {
                float a00 = m[0][0], a01 = m[0][1], a02 = m[0][2];
                float a10 = m[1][0], a11 = m[1][1], a12 = m[1][2];
                float a20 = m[2][0], a21 = m[2][1], a22 = m[2][2];
                float b01 = a22 * a11 - a12 * a21;
                float b11 = -a22 * a10 + a12 * a20;
                float b21 = a21 * a10 - a11 * a20;
                float det = a00 * b01 + a01 * b11 + a02 * b21;
                float invdet = abs(det) > 0.000001 ? 1.0 / det : 0.0;
                return float3x3(
                    float3(b01, -a22 * a01 + a02 * a21, a12 * a01 - a02 * a11) * invdet,
                    float3(b11, a22 * a00 - a02 * a20, -a12 * a00 + a02 * a10) * invdet,
                    float3(b21, -a21 * a00 + a01 * a20, a11 * a00 - a01 * a10) * invdet
                );
            }
            inline float3 wpe_perspective_texcoord(float2 uv, float2 p0, float2 p1, float2 p2, float2 p3) {
                // WPE: mul(vec3(uv,1), inverse(squareToQuad(...))); WPE mul(x,y) == y * x.
                return wpe_mat3_inverse(wpe_square_to_quad(p0, p1, p2, p3)) * float3(uv, 1.0);
            }
            // reflection.vert (PERSPECTIVE=0) v_ReflectedCoord: mirror uv across the horizontal
            // centre (offset shifts the mirror line), then rotate by g_Direction. Transcribed
            // verbatim, no V flip — our fullscreen in.uv already matches WPE a_TexCoord (both
            // top-left, uv.y==0 at the top; `wpe_fullscreen_vertex`). Without it the varying fell
            // back to raw in.uv, so the reflected sample == albedo (no-op) and water showed its flat base colour instead of the mirrored sky (3413921910: solid pink band across the water).
            inline float2 wpe_reflection_texcoord(float2 uv, float direction, float offset) {
                float2 center = float2(0.5, 0.5);
                float2 delta = uv - center;
                delta.y += offset;
                delta.y = -delta.y;
                delta = wpe_rotate_vec2(delta, direction);
                return center + delta;
            }
            """
        )
    }

    private static func varyingInitializer(
        for varying: WPEVaryingDecl,
        shaderName: String,
        availableUniforms: Set<String>,
        comboValues: [String: Int] = [:]
    ) -> String {
        // `v_DirectionN` = normalize(g_SpinCenter(N+1) − g_SpinCenterN); gated on those uniforms so it never intercepts dualwaves' `v_Direction2`.
        if ["float2", "float4"].contains(varying.metalType),
           varying.name.hasPrefix("v_Direction"),
           let nodeIndex = Int(varying.name.dropFirst("v_Direction".count)),
           nodeIndex >= 1, nodeIndex <= 10,
           hasUniforms("g_SpinCenter\(nodeIndex)", "g_SpinCenter\(nodeIndex + 1)", in: availableUniforms) {
            let raw = "wpe_safe_normalize(g_SpinCenter\(nodeIndex + 1) - g_SpinCenter\(nodeIndex))"
            if varying.metalType == "float4" {
                // .zw carries the g_DirectionOffset-rotated direction only under GLOBAL_ROTATION.
                let rotated = comboValues["GLOBAL_ROTATION"] == 1 && availableUniforms.contains("g_DirectionOffset")
                    ? "wpe_rotate_vec2(\(raw), g_DirectionOffset)"
                    : raw
                return "float4(\(raw), \(rotated))"
            }
            return raw
        }
        switch varying.name {
        case "v_TexCoord":
            // TRANSFORM bar UV: `applyFx` divides by scale where fade multiplies — do not share one helper.
            if varying.metalType == "float2",
               texCoordZWFamilyName(shaderName: shaderName) == "simple_audio_bars",
               comboValues["TRANSFORM"] == 1,
               hasUniforms("g_Offset", "g_Scale", "g_Direction", in: availableUniforms) {
                return "(wpe_rotate_vec2(in.uv - 0.5, -g_Direction) + g_Offset) / max(g_Scale, float2(1e-6)) + 0.5"
            }
            if varying.metalType == "float2" {
                return "in.uv"
            }
            // swing/twirl pack aspect + sine phase into .zw; rebuild before the resolution-scaled-UV path which would mis-fill .zw.
            if varying.metalType == "float4",
               let family = texCoordZWFamilyName(shaderName: shaderName),
               family == "swing" || family == "twirl",
               hasUniforms("g_Time", "g_Speed", "g_Phase", "g_Amount", "g_Texture0Resolution", in: availableUniforms) {
                let components = family == "swing" ? "xy" : "zw"
                return "wpe_swing_texcoord(in.uv, g_Texture0Resolution.\(components), g_Time, g_Speed, g_Phase, g_Amount)"
            }
            // `.zw` is the single-axis per-tap step, not a scaled UV; must precede the resolution ladder or blur13a averages the whole frame.
            if varying.metalType == "float4",
               texCoordZWFamilyName(shaderName: shaderName) == "blur_precise_gaussian",
               hasUniforms("g_Scale", "g_Texture0Resolution", in: availableUniforms) {
                return comboValues["VERTICAL"] == 1
                    ? "float4(in.uv, 0.0, g_Scale.y / g_Texture0Resolution.w)"
                    : "float4(in.uv, g_Scale.x / g_Texture0Resolution.z, 0.0)"
            }
            // `.xy` is the zoomed pixel coordinate and `.zw` the aspect·size divisor; both must precede the resolution ladder.
            if varying.metalType == "float4",
               texCoordZWFamilyName(shaderName: shaderName) == "lens_distortion",
               hasLensDistortionUniforms(availableUniforms) {
                return "float4((in.uv - 0.5) * (1.0 + (1.0 - u_zoom) * u_general) + 0.5, "
                    + "float2(wpe_safe_ratio(g_Texture0Resolution.y, g_Texture0Resolution.x), 1.0) "
                    + "* max(1e-6, u_size * 4.0))"
            }
            if varying.metalType == "float4",
               let resolutionUniform = texCoordResolutionUniform(
                shaderName: shaderName,
                availableUniforms: availableUniforms,
                comboValues: comboValues
               ) {
                return "wpe_texcoord_with_resolution(in.uv, \(resolutionUniform))"
            }
        case "p_TexCoord":
            // fade `p_TexCoord` is offset/rotated/scaled independently of `v_TexCoord`. Simple_Audio_Bars writes `p_TexCoord = a_TexCoord`, so it has no rule here.
            if varying.metalType == "float2",
               texCoordZWFamilyName(shaderName: shaderName) == "fade",
               hasUniforms("g_Offset", "g_Scale", "g_Direction", in: availableUniforms) {
                return "wpe_rotate_vec2(in.uv - g_Offset - 0.5, -g_Direction) * g_Scale + 0.5"
            }
        case "i_DCorrectingFactor":
            // Aspect that keeps rounded bar caps circular. Declared only under BAR_STYLE 1; DEFORMITY 3 (Adaptive) is the default that reads it.
            if varying.metalType == "float",
               texCoordZWFamilyName(shaderName: shaderName) == "simple_audio_bars",
               availableUniforms.contains("g_Texture0Resolution") {
                guard (comboValues["DEFORMITY"] ?? 3) == 3 else { return "1.0" }
                // LEFT/RIGHT/CENTER_H/STEREO_H lay the bars out horizontally and invert it.
                let horizontal = [2, 3, 6, 8].contains(comboValues["SHAPE"] ?? 0)
                return horizontal
                    ? "wpe_safe_ratio(g_Texture0Resolution.y, g_Texture0Resolution.x)"
                    : "wpe_safe_ratio(g_Texture0Resolution.x, g_Texture0Resolution.y)"
            }
        case "v_Distorsion":
            // `.xy` is barrel/pincushion strength, `.zw` the CA split; a screen-UV fallback makes them equal and cancels the blue tap.
            if varying.metalType == "float4",
               texCoordZWFamilyName(shaderName: shaderName) == "lens_distortion",
               hasLensDistortionUniforms(availableUniforms) {
                let amount = "(float2(u_distorsion1, u_distorsion2 + u_distorsion2) * -u_general)"
                // CA defaults to 1 in the .vert's own [COMBO] annotation.
                let aberration = (comboValues["CA"] ?? 1) == 1
                    ? "u_aberration * 0.1 * \(amount)"
                    : "float2(0.0)"
                return "float4(\(amount), \(aberration))"
            }
        case "v_Transforms":
            // `.xy` recentres the distorted sample; `.zw` is ANAMORPHIC rotation and is only read under that combo.
            if varying.metalType == "float4",
               texCoordZWFamilyName(shaderName: shaderName) == "lens_distortion",
               hasLensDistortionUniforms(availableUniforms) {
                let rotation = comboValues["ANAMORPHIC"] == 1
                    ? "float2(cos(-u_angle), sin(-u_angle))"
                    : "float2(0.0)"
                return "float4((1.0 - u_center - 0.5) * u_general - 0.5, \(rotation))"
            }
        case "v_TexCoordMask":
            if varying.metalType == "float4",
               availableUniforms.contains("g_Texture3Resolution") {
                return "wpe_texcoord_mask(in.uv, g_Texture3Resolution)"
            }
            // Family-gated: a float2 `v_TexCoordMask` reads slot 1, 2, or 3 depending on the effect; the wrong resolution is worse than the raw-UV fallback.
            if varying.metalType == "float2",
               texCoordZWFamilyName(shaderName: shaderName) == "blur_precise_gaussian",
               availableUniforms.contains("g_Texture2Resolution") {
                return "wpe_texcoord_mask(in.uv, g_Texture2Resolution).xy"
            }
        case "v_TexCoordLeftTop":
            // LeftTop = uv.xyxy then .x -= texel.x, .w += texel.y. A screen-UV fallback collapses neighbour taps onto one texel.
            if varying.metalType == "float4",
               availableUniforms.contains("g_Texture0Resolution") {
                return "float4(in.uv.x - 1.0 / g_Texture0Resolution.x, in.uv.y, in.uv.x, in.uv.y + 1.0 / g_Texture0Resolution.y)"
            }
        case "v_TexCoordRightBottom":
            // Mirror of v_TexCoordLeftTop: .x += texel.x, .w -= texel.y.
            if varying.metalType == "float4",
               availableUniforms.contains("g_Texture0Resolution") {
                return "float4(in.uv.x + 1.0 / g_Texture0Resolution.x, in.uv.y, in.uv.x, in.uv.y - 1.0 / g_Texture0Resolution.y)"
            }
        case "v_StepSize":
            // Per-texel box-blur step `1 / vec4(-res.xy, res.xy)`; the float4(uv,uv) default would feed screen position as a sample offset.
            if varying.metalType == "float4",
               availableUniforms.contains("g_Texture0Resolution") {
                return "1.0 / float4(-g_Texture0Resolution.xy, g_Texture0Resolution.xy)"
            }
        case "v_SizeMultiplier":
            // `vec2(aRatio, 1) * (u_radius+u_radius) * iterations * g_TexelSize`; aRatio is u_ratio under ANAMORPHIC else 1; iterations 0.675 under HIGH_QUALITY else 1.5.
            if varying.metalType == "float2",
               hasUniforms("g_TexelSize", "u_radius", in: availableUniforms) {
                let aRatio = comboValues["ANAMORPHIC"] == 1 && availableUniforms.contains("u_ratio")
                    ? "u_ratio" : "1.0"
                let iterations = comboValues["HIGH_QUALITY"] == 1 ? "0.675" : "1.5"
                return "float2(\(aRatio), 1.0) * (u_radius + u_radius) * \(iterations) * g_TexelSize"
            }
        case "v_Scroll":
            if varying.metalType == "float2",
               hasUniforms("g_ScrollX", "g_ScrollY", "g_Time", in: availableUniforms) {
                return "wpe_scroll_vector(g_ScrollX, g_ScrollY, g_Time)"
            }
        case "v_Direction":
            if varying.metalType == "float2",
               availableUniforms.contains("g_Direction") {
                return "wpe_rotate_vec2(float2(0.0, 1.0), g_Direction)"
            }
        case "v_Direction2":
            if varying.metalType == "float2",
               availableUniforms.contains("g_Direction2") {
                return "wpe_rotate_vec2(float2(0.0, 1.0), g_Direction2)"
            }
        case "v_ReflectedCoord":
            // PERSPECTIVE=0: vertical mirror + offset, rotated by g_Direction. Falling through to raw in.uv makes the reflected sample identical to albedo.
            if varying.metalType == "float2",
               hasUniforms("g_Direction", "g_ReflectionOffset", in: availableUniforms) {
                return "wpe_reflection_texcoord(in.uv, g_Direction, g_ReflectionOffset)"
            }
        case "v_TexCoordPerspective", "v_TexCoordFx":
            // Homogeneous `mul(vec3(uv,1), inverse(squareToQuad(g_Point0..3)))`. lightshafts' fragment does its own `.xy/.z` divide, so the raw float3 is correct.
            if varying.metalType == "float3",
               hasUniforms("g_Point0", "g_Point1", "g_Point2", "g_Point3", in: availableUniforms) {
                return "wpe_perspective_texcoord(in.uv, g_Point0, g_Point1, g_Point2, g_Point3)"
            }
            if varying.metalType == "float3" {
                return "float3(in.uv, 1.0)"
            }
        case "v_PerspCoord":
            // squareToQuad only under PERSPECTIVE=1; default is raw UV with z=1. Unconditional perspective can clamp the waveform out.
            if varying.metalType == "float3" {
                if comboValues["PERSPECTIVE"] == 1,
                   hasUniforms("g_Point0", "g_Point1", "g_Point2", "g_Point3", in: availableUniforms) {
                    return "wpe_perspective_texcoord(in.uv, g_Point0, g_Point1, g_Point2, g_Point3)"
                }
                return "float3(in.uv, 1.0)"
            }
        case "v_ViewCoord":
            // Conservative reconstruction of `v_ViewCoord.xy / v_ViewCoord.z * 0.5 + 0.5`: homogeneous z=1 mapped back to the current quad UV.
            if varying.metalType == "float3" {
                return "float3(in.uv * 2.0 - 1.0, 1.0)"
            }
        case "audioValue":
            if varying.metalType == "float4" {
                return "float4(0.0)"
            }
        case "v_TexCoordRipple":
            if varying.metalType == "float4",
               hasUniforms(
                "g_Time",
                "g_AnimationSpeed",
                "g_ScrollSpeed",
                "g_Direction",
                "g_Ratio",
                "g_Scale",
                "g_Texture0Resolution",
                in: availableUniforms
               ) {
                return "wpe_ripple_texcoord(in.uv, g_Time, g_AnimationSpeed, g_ScrollSpeed, g_Direction, g_Ratio, g_Scale, g_Texture0Resolution)"
            }
        case "v_TexCoordIris":
            if varying.metalType == "float2",
               hasUniforms(
                "g_Time",
                "g_Speed",
                "g_PhaseOffset",
                "g_Rough",
                "g_NoiseAmount",
                "g_Scale",
                in: availableUniforms
               ) {
                return "wpe_iris_texcoord(g_Time, g_Speed, g_PhaseOffset, g_Rough, g_NoiseAmount, g_Scale)"
            }
        case "v_TexCoordNoise":
            // foliage variant: tiled noise rotated by g_Direction (needs g_Ratio too).
            if varying.metalType == "float4",
               hasUniforms(
                "g_NoiseScale",
                "g_Ratio",
                "g_Direction",
                "g_Texture0Resolution",
                in: availableUniforms
               ) {
                return "wpe_foliage_texcoord_noise(in.uv, g_NoiseScale, g_Ratio, g_Direction, g_Texture0Resolution)"
            }
            // filmgrain: two frac(time)-scrolled lookups. No g_Ratio/g_Direction, so it cannot reuse the foliage helper.
            if varying.metalType == "float4",
               hasUniforms("g_NoiseScale", "g_Time", "g_Texture0Resolution", in: availableUniforms) {
                return "wpe_filmgrain_texcoord_noise(in.uv, g_Time, g_NoiseScale, g_Texture0Resolution)"
            }
        case "v_Params":
            if varying.metalType == "float3",
               hasUniforms("g_Direction", "g_Strength", in: availableUniforms) {
                return "wpe_foliage_params(in.uv, g_Direction, g_Strength)"
            }
        case "v_equalScaleFactor":
            // multistage_wave.vert: aspect-correction factor (≥1 per axis), NOT screen UV.
            // Defaulting to in.uv stretched the wave field horizontally across the frame.
            if varying.metalType == "float2",
               availableUniforms.contains("g_Texture0Resolution") {
                return "float2(max(1.0, wpe_safe_ratio(g_Texture0Resolution.x, g_Texture0Resolution.y)), max(1.0, wpe_safe_ratio(g_Texture0Resolution.y, g_Texture0Resolution.x)))"
            }
        case "v_Pulse":
            // AUDIOPROCESSING → CreateAudioResponse (0 when silent); else a time-driven sine. Must not default to in.uv.x.
            if varying.metalType == "float" {
                let mode = comboValues["AUDIOPROCESSING"] ?? 0
                if mode != 0,
                   hasUniforms(
                    "g_AudioSpectrum16Left", "g_AudioSpectrum16Right",
                    "g_AudioFrequencyMin", "g_AudioFrequencyMax",
                    "g_AudioBounds", "g_AudioPower", "g_AudioMultiply",
                    in: availableUniforms
                   ) {
                    return "wpe_audio_response16(g_AudioSpectrum16Left, g_AudioSpectrum16Right, \(mode), g_AudioFrequencyMin, g_AudioFrequencyMax, g_AudioBounds, g_AudioPower, g_AudioMultiply)"
                }
                if hasUniforms("g_Time", "g_PulseThresholds", "g_PulseSpeed", "g_PulsePhase", "g_PulseAmount", in: availableUniforms) {
                    return "wpe_pulse_response(g_Time, g_PulseThresholds, g_PulseSpeed, g_PulsePhase, g_PulseAmount)"
                }
                return "0.0"
            }
        case "v_ParallaxOffset":
            // Use `g_ParallaxPosition` (neutral 0.5 when centered); the full matrix form is excluded from fragment injection.
            if varying.metalType == "float2" {
                return availableUniforms.contains("g_ParallaxPosition") ? "g_ParallaxPosition" : "float2(0.5)"
            }
        case "v_Bounds":
            if varying.metalType == "float2",
               availableUniforms.contains("g_Bounds") {
                return "wpe_bounds_vector(g_Bounds)"
            }
        case "v_Cycles":
            // Four scroll-loop phases bounded to ±0.5 so displacement oscillates instead of growing with screen position.
            if varying.metalType == "float4",
               hasUniforms("g_Time", "g_FlowSpeed", in: availableUniforms) {
                return "wpe_waterflow_cycles(g_Time, g_FlowSpeed)"
            }
        case "v_Blend":
            // waterflow.vert: smoothstep cross-fade weights between the two phase samples.
            if varying.metalType == "float2",
               hasUniforms("g_Time", "g_FlowSpeed", "g_PhaseFeather", in: availableUniforms) {
                return "wpe_waterflow_blend(g_Time, g_FlowSpeed, g_PhaseFeather)"
            }
        case "v_AudioShift":
            // Reconstruct CreateAudioResponse so the varying rests at 0 when silent instead of defaulting to in.uv.x.
            if varying.metalType == "float",
               hasUniforms(
                "g_AudioSpectrum16Left",
                "g_AudioSpectrum16Right",
                "g_AudioFrequencyMin",
                "g_AudioFrequencyMax",
                "g_AudioBounds",
                "g_AudioPower",
                "g_AudioMultiply",
                in: availableUniforms
               ) {
                let mode = comboValues["AUDIOPROCESSING"] ?? 1
                return "wpe_audio_response16(g_AudioSpectrum16Left, g_AudioSpectrum16Right, \(mode), g_AudioFrequencyMin, g_AudioFrequencyMax, g_AudioBounds, g_AudioPower, g_AudioMultiply)"
            }
            return "0.0"
        case "v_AudioPulse":
            // Reconstruct CreateAudioResponse when spectrum uniforms are present; otherwise 0 (silent), like v_AudioShift.
            if varying.metalType == "float" {
                let mode = comboValues["AUDIOPROCESSING"] ?? 1
                if hasUniforms(
                    "g_AudioSpectrum16Left", "g_AudioSpectrum16Right",
                    "g_AudioFrequencyMin", "g_AudioFrequencyMax",
                    "g_AudioBounds", "g_AudioPower", "g_AudioMultiply",
                    in: availableUniforms
                ) {
                    return "wpe_audio_response16(g_AudioSpectrum16Left, g_AudioSpectrum16Right, \(mode), g_AudioFrequencyMin, g_AudioFrequencyMax, g_AudioBounds, g_AudioPower, g_AudioMultiply)"
                }
                return "0.0"
            }
        default:
            break
        }

        switch varying.metalType {
        case "float2":
            return "in.uv"
        case "float3":
            return "float3(in.uv, 0.0)"
        case "float4":
            return "float4(in.uv, in.uv)"
        case "float":
            return "in.uv.x"
        default:
            return "\(varying.metalType)(0)"
        }
    }

    /// The generic array path would call `varyingInitializer` once and repeat it, collapsing the 4-tap box filter to a point sample.
    private static func texCoordBoxFilterInitializers(
        varying: WPEVaryingDecl,
        availableUniforms: Set<String>
    ) -> [String]? {
        guard varying.name == "v_TexCoord",
              varying.metalType == "float2",
              varying.arrayLength == 4,
              availableUniforms.contains("g_Texture0Resolution") else {
            return nil
        }
        return [
            "in.uv - (1.0 / g_Texture0Resolution.xy)",
            "in.uv + float2(1.0 / g_Texture0Resolution.x, -1.0 / g_Texture0Resolution.y)",
            "in.uv + float2(-1.0 / g_Texture0Resolution.x, 1.0 / g_Texture0Resolution.y)",
            "in.uv + (1.0 / g_Texture0Resolution.xy)",
        ]
    }

    private static func symbolicArrayReconstructionLines(
        for varying: WPEVaryingDecl,
        availableUniforms: Set<String>,
        comboValues: [String: Int]
    ) -> [String] {
        guard varying.name == "audioValue",
              varying.metalType == "float4" else {
            return []
        }

        // The spectrum arrays only come in these three sizes, and the loop below
        // indexes them up to `resolution`: any other combo value read past the array.
        let requested = comboValues["RESOLUTION"] ?? 32
        let resolution = [16, 32, 64].contains(requested) ? requested : 32
        let leftName: String
        let rightName: String
        switch resolution {
        case 16:
            leftName = "g_AudioSpectrum16Left"
            rightName = "g_AudioSpectrum16Right"
        case 64:
            leftName = "g_AudioSpectrum64Left"
            rightName = "g_AudioSpectrum64Right"
        default:
            leftName = "g_AudioSpectrum32Left"
            rightName = "g_AudioSpectrum32Right"
        }

        guard hasUniforms(leftName, rightName, "u_ampExponent", "u_FreqBalance", "u_LRBalance", in: availableUniforms) else {
            return []
        }

        let equalize = comboValues["EQUALIZE"] ?? 0
        return [
            "    for (int wpeAudioIndex = 0; wpeAudioIndex < \(resolution); wpeAudioIndex += 4) {",
            "        \(varying.name)[wpeAudioIndex / 4] = float4(",
            "            wpe_audio_oscilloscope_value(\(leftName)[wpeAudioIndex + 0], \(rightName)[wpeAudioIndex + 0], wpeAudioIndex + 0, \(resolution), \(equalize), u_LRBalance, u_FreqBalance, u_ampExponent),",
            "            wpe_audio_oscilloscope_value(\(leftName)[wpeAudioIndex + 1], \(rightName)[wpeAudioIndex + 1], wpeAudioIndex + 1, \(resolution), \(equalize), u_LRBalance, u_FreqBalance, u_ampExponent),",
            "            wpe_audio_oscilloscope_value(\(leftName)[wpeAudioIndex + 2], \(rightName)[wpeAudioIndex + 2], wpeAudioIndex + 2, \(resolution), \(equalize), u_LRBalance, u_FreqBalance, u_ampExponent),",
            "            wpe_audio_oscilloscope_value(\(leftName)[wpeAudioIndex + 3], \(rightName)[wpeAudioIndex + 3], wpeAudioIndex + 3, \(resolution), \(equalize), u_LRBalance, u_FreqBalance, u_ampExponent)",
            "        );",
            "    }"
        ]
    }

    static func hasUniforms(_ names: String..., in availableUniforms: Set<String>) -> Bool {
        names.allSatisfy { availableUniforms.contains($0) }
    }

    private static func texCoordResolutionUniform(
        shaderName: String,
        availableUniforms: Set<String>,
        comboValues: [String: Int] = [:]
    ) -> String? {
        let lowercased = shaderName.lowercased()
        // A verified family uses its exact resolution slot; the mask/aux texture is not always g_Texture1.
        if let slot = texCoordZWResolutionSlot(shaderName: shaderName, comboValues: comboValues) {
            // Do not fall through to the generic ladder for a recognized family: a missing exact-slot resolution would scale .zw by a different texture.
            let uniform = "g_Texture\(slot)Resolution"
            return availableUniforms.contains(uniform) ? uniform : nil
        }
        // MASK uses g_Texture1, TIMEOFFSET uses g_Texture2. A combo-blind pick of g_Texture1Resolution mis-scales TIMEOFFSET.
        if comboValues["MASK"] == 1, availableUniforms.contains("g_Texture1Resolution") {
            return "g_Texture1Resolution"
        }
        if comboValues["TIMEOFFSET"] == 1, availableUniforms.contains("g_Texture2Resolution") {
            return "g_Texture2Resolution"
        }
        if lowercased.contains("pulse"), availableUniforms.contains("g_Texture2Resolution") {
            return "g_Texture2Resolution"
        }
        if availableUniforms.contains("g_Texture1Resolution") {
            return "g_Texture1Resolution"
        }
        if availableUniforms.contains("g_Texture2Resolution") {
            return "g_Texture2Resolution"
        }
        return nil
    }

    static func textureSlot(for name: String) -> Int? {
        let prefix = "g_Texture"
        guard name.hasPrefix(prefix) else { return nil }
        return Int(name.dropFirst(prefix.count))
    }
}
#endif
