#if !LITE_BUILD
import Foundation
import LiveWallpaperProWPE

extension WPEShaderTranspiler {
    // MARK: - Render

    /// Emit the final MSL source with the fixed parameter signature so the dispatcher knows what to bind without doing runtime reflection.
    static func renderMSL(
        shaderName: String,
        uniforms: [WPEUniformDecl],
        samplers: [WPESamplerDecl],
        varyings: [WPEVaryingDecl],
        helpers: String,
        mainBody: String,
        mutableGlobals: [ProgramScopeMutableDecl] = [],
        comboValues: [String: Int] = [:],
        premultipliedInputSlots: Set<Int> = [],
        premultipliedOutput: Bool = false
    ) -> String {
        let warningCleanHelpers = neutralizeMetalStdlibMacroRedefinitions(helpers)
        let warningCleanMainBody = neutralizeMetalStdlibMacroRedefinitions(mainBody)
        var out: [String] = [
            "#include <metal_stdlib>",
            "using namespace metal;",
            "",
            "// Generated by WPEShaderTranspiler from \(shaderName).",
            ""
        ]

        out.append("struct WPEStageIn {")
        out.append("    float4 position [[position]];")
        out.append("    float2 uv;")
        out.append("};")
        out.append("")

        if !uniforms.isEmpty {
            // Size to this shader's own slot count, not `uniformSlotMaximum`: the host binds exactly
            // `totalSlots × 16` bytes, and Metal validation rejects a buffer shorter than the struct.
            let totalSlots = uniforms.reduce(0) { $0 + ($1.arrayLength ?? slotCount(for: $1.type)) }
            out.append("struct WPEUniforms {")
            out.append("    float4 vals[\(max(totalSlots, 1))];")
            out.append("};")
            out.append("")
        }

        out.append("[[maybe_unused]] constexpr sampler linearSampler(address::clamp_to_edge, filter::linear);")
        out.append("[[maybe_unused]] constexpr sampler repeatSampler(address::repeat, filter::linear);")
        out.append("inline float min(int lhs, float rhs) { return metal::min(float(lhs), rhs); }")
        out.append("inline float min(float lhs, int rhs) { return metal::min(lhs, float(rhs)); }")
        out.append("inline float max(int lhs, float rhs) { return metal::max(float(lhs), rhs); }")
        out.append("inline float max(float lhs, int rhs) { return metal::max(lhs, float(rhs)); }")
        out.append("inline float clamp(int value, float lower, float upper) { return metal::clamp(float(value), lower, upper); }")
        out.append("inline float clamp(float value, int lower, float upper) { return metal::clamp(value, float(lower), upper); }")
        out.append("inline float clamp(float value, float lower, int upper) { return metal::clamp(value, lower, float(upper)); }")
        out.append("inline float clamp(int value, int lower, float upper) { return metal::clamp(float(value), float(lower), upper); }")
        out.append("inline float clamp(int value, float lower, int upper) { return metal::clamp(float(value), lower, float(upper)); }")
        out.append("inline float clamp(float value, int lower, int upper) { return metal::clamp(value, float(lower), float(upper)); }")
        out.append("inline float wpe_smoothstep(float edge0, float edge1, float x) {")
        out.append("    float width = edge1 - edge0;")
        out.append("    if (abs(width) <= 1.0e-7) { return x < edge0 ? 0.0 : 1.0; }")
        out.append("    float t = metal::clamp((x - edge0) / width, 0.0, 1.0);")
        out.append("    return t * t * (3.0 - 2.0 * t);")
        out.append("}")
        out.append("inline float2 wpe_smoothstep(float2 edge0, float2 edge1, float2 x) { return float2(wpe_smoothstep(edge0.x, edge1.x, x.x), wpe_smoothstep(edge0.y, edge1.y, x.y)); }")
        out.append("inline float3 wpe_smoothstep(float3 edge0, float3 edge1, float3 x) { return float3(wpe_smoothstep(edge0.x, edge1.x, x.x), wpe_smoothstep(edge0.y, edge1.y, x.y), wpe_smoothstep(edge0.z, edge1.z, x.z)); }")
        out.append("inline float4 wpe_smoothstep(float4 edge0, float4 edge1, float4 x) { return float4(wpe_smoothstep(edge0.x, edge1.x, x.x), wpe_smoothstep(edge0.y, edge1.y, x.y), wpe_smoothstep(edge0.z, edge1.z, x.z), wpe_smoothstep(edge0.w, edge1.w, x.w)); }")
        out.append("inline float2 wpe_smoothstep(float edge0, float edge1, float2 x) { return wpe_smoothstep(float2(edge0), float2(edge1), x); }")
        out.append("inline float3 wpe_smoothstep(float edge0, float edge1, float3 x) { return wpe_smoothstep(float3(edge0), float3(edge1), x); }")
        out.append("inline float4 wpe_smoothstep(float edge0, float edge1, float4 x) { return wpe_smoothstep(float4(edge0), float4(edge1), x); }")
        if !premultipliedInputSlots.isEmpty {
            // Recover straight-alpha color from a premultiplied render-target
            // sample so the original WPE shader math operates in straight space.
            out.append("inline float4 wpe_unpremultiply_sample(float4 color) {")
            out.append("    float a = color.a;")
            out.append("    color.rgb = a > 0.00001 ? color.rgb / a : float3(0.0);")
            out.append("    return color;")
            out.append("}")
        }
        if premultipliedOutput {
            // Premultiply the shader's straight-alpha output for the
            // premultiplied render-target pipeline.
            out.append("inline float4 wpe_premultiply_output(float4 color) {")
            out.append("    float a = metal::clamp(color.a, 0.0, 1.0);")
            out.append("    return float4(color.rgb * a, a);")
            out.append("}")
        }
        appendCompatibilityPrelude(
            to: &out,
            helpers: warningCleanHelpers,
            comboValues: comboValues
        )
        out.append("")

        if !warningCleanHelpers.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            out.append(warningCleanHelpers)
            out.append("")
        }

        var signature = ["fragment float4 wpe_translated_fragment("]
        signature.append("    WPEStageIn in [[stage_in]],")
        if !uniforms.isEmpty {
            signature.append("    constant WPEUniforms& u [[buffer(0)]],")
        }
        for slot in 0..<Self.customTextureSlotCount {
            signature.append("    texture2d<float> tex\(slot) [[texture(\(slot))]],")
        }
        // Per-slot samplers. Address mode (clamp vs repeat) and filter (linear vs
        // nearest) are bound at runtime from each texture's TEXI flags in
        // WPEMetalRenderExecutor's custom-shader dispatch. This replaces the old
        // annotation heuristic that clamp-sampled every content texture — which
        // froze scrolled tiling maps (water-normal, noise, flow) the moment their
        // sample UVs left [0,1]. Direct `g_TextureN` reads use `wpeSamplerN`; helper
        // samples fall back to the file-scope clamp/repeat constants.
        for slot in 0..<Self.customTextureSlotCount {
            let comma = slot < Self.customTextureSlotCount - 1 ? "," : ""
            signature.append("    sampler wpeSampler\(slot) [[sampler(\(slot))]]\(comma)")
        }
        signature.append(") {")
        out.append(signature.joined(separator: "\n"))

        // Alias each sampler to its ACTUAL texture slot (`g_Texture2` → tex2),
        // matching how the custom-shader dispatcher binds textures
        // (`setFragmentTexture(index: slot)`). Enumeration order would mis-map
        // any sparse / non-zero slot (`g_Texture2` → tex0) and sample the wrong
        // texture. Non-`g_TextureN` samplers (no parsed slot) keep enumeration
        // order as before.
        for (index, sampler) in samplers.enumerated() {
            let slot = Self.textureSlot(for: sampler.name) ?? index
            out.append("    [[maybe_unused]] auto \(sampler.name) = tex\(slot);")
        }
        var slotCursor = 0
        for u in uniforms {
            if let arrayLength = u.arrayLength {
                let elementType: String
                switch u.type {
                case "vec2": elementType = "float2"
                case "vec3": elementType = "float3"
                case "vec4": elementType = "float4"
                case "int":  elementType = "int"
                case "bool": elementType = "bool"
                default:     elementType = "float"
                }
                out.append("    [[maybe_unused]] \(elementType) \(u.name)[\(arrayLength)];")
                for i in 0..<arrayLength {
                    let read: String
                    switch elementType {
                    case "float2": read = "u.vals[\(slotCursor + i)].xy"
                    case "float3": read = "u.vals[\(slotCursor + i)].xyz"
                    case "float4": read = "u.vals[\(slotCursor + i)]"
                    case "int":    read = "int(u.vals[\(slotCursor + i)].x)"
                    case "bool":   read = "u.vals[\(slotCursor + i)].x > 0.5"
                    default:       read = "u.vals[\(slotCursor + i)].x"
                    }
                    out.append("    \(u.name)[\(i)] = \(read);")
                }
                slotCursor += arrayLength
                continue
            }
            let slots = Self.slotCount(for: u.type)
            switch u.type {
            case "float":
                out.append("    [[maybe_unused]] float \(u.name) = u.vals[\(slotCursor)].x;")
            case "vec2":
                out.append("    [[maybe_unused]] float2 \(u.name) = u.vals[\(slotCursor)].xy;")
            case "vec3":
                out.append("    [[maybe_unused]] float3 \(u.name) = u.vals[\(slotCursor)].xyz;")
            case "vec4":
                out.append("    [[maybe_unused]] float4 \(u.name) = u.vals[\(slotCursor)];")
            case "int":
                out.append("    [[maybe_unused]] int \(u.name) = int(u.vals[\(slotCursor)].x);")
            case "ivec2":
                out.append("    [[maybe_unused]] int2 \(u.name) = int2(u.vals[\(slotCursor)].xy);")
            case "ivec3":
                out.append("    [[maybe_unused]] int3 \(u.name) = int3(u.vals[\(slotCursor)].xyz);")
            case "ivec4":
                out.append("    [[maybe_unused]] int4 \(u.name) = int4(u.vals[\(slotCursor)]);")
            case "bool":
                out.append("    [[maybe_unused]] bool \(u.name) = u.vals[\(slotCursor)].x > 0.5;")
            case "bvec2":
                out.append("    [[maybe_unused]] bool2 \(u.name) = u.vals[\(slotCursor)].xy > float2(0.5);")
            case "bvec3":
                out.append("    [[maybe_unused]] bool3 \(u.name) = u.vals[\(slotCursor)].xyz > float3(0.5);")
            case "bvec4":
                out.append("    [[maybe_unused]] bool4 \(u.name) = u.vals[\(slotCursor)] > float4(0.5);")
            case "mat2":
                out.append("    [[maybe_unused]] float2x2 \(u.name) = float2x2(u.vals[\(slotCursor)].xy, u.vals[\(slotCursor + 1)].xy);")
            case "mat3":
                out.append("    [[maybe_unused]] float3x3 \(u.name) = float3x3(u.vals[\(slotCursor)].xyz, u.vals[\(slotCursor + 1)].xyz, u.vals[\(slotCursor + 2)].xyz);")
            case "mat4":
                out.append("    [[maybe_unused]] float4x4 \(u.name) = float4x4(u.vals[\(slotCursor)], u.vals[\(slotCursor + 1)], u.vals[\(slotCursor + 2)], u.vals[\(slotCursor + 3)]);")
            default:
                out.append("    [[maybe_unused]] \(u.metalType) \(u.name) = u.vals[\(slotCursor)].x;")
            }
            slotCursor += slots
        }

        let uniformNames = Set(uniforms.map(\.name))
        let autoSwayReconstruction = autoSwayVaryingReconstructionLines(
            varyings: varyings,
            availableUniforms: uniformNames,
            comboValues: comboValues
        )
        // Screen-UV fallbacks produced when no reconstruction rule matched a varying.
        // A non-v_TexCoord varying that the fragment actually uses but lands here renders
        // incorrectly (a 0→1 UV ramp standing in for vertex-computed data) — emit a marker
        // in the generated MSL so the gap is visible in scene-debug dumps instead of silent.
        let uvFallbackInitializers: Set<String> = [
            "in.uv", "in.uv.x", "float4(in.uv, in.uv)", "float3(in.uv, 0.0)",
        ]
        for varying in varyings {
            if varying.name == "uv" { continue }
            let initializer = varyingInitializer(
                for: varying,
                shaderName: shaderName,
                availableUniforms: uniformNames,
                comboValues: comboValues
            )
            if varying.name != "v_TexCoord",
               uvFallbackInitializers.contains(initializer),
               !autoSwayReconstruction.contains(where: { $0.contains(" \(varying.name) = ") }),
               warningCleanMainBody.range(of: "\\b\(NSRegularExpression.escapedPattern(for: varying.name))\\b", options: .regularExpression) != nil {
                out.append("    // WPE-DIAGNOSTIC: varying '\(varying.name)' has no reconstruction rule and fell back to a screen-UV default; this likely renders incorrectly.")
            }
            if let arrayLength = varying.arrayLength {
                let initializers = texCoordBoxFilterInitializers(varying: varying, availableUniforms: uniformNames)
                    ?? Array(repeating: initializer, count: arrayLength)
                out.append("    [[maybe_unused]] \(varying.metalType) \(varying.name)[\(arrayLength)] = { \(initializers.joined(separator: ", ")) };")
            } else if let arrayDimension = varying.arrayDimension {
                // Symbolic, #define-sized array: we can't expand a literal initializer list at
                // transpile time, so zero-init, then let known vertex-varying reconstructions
                // fill the slots they need.
                out.append("    [[maybe_unused]] \(varying.metalType) \(varying.name)[\(arrayDimension)] = {};")
                out.append(
                    contentsOf: symbolicArrayReconstructionLines(
                        for: varying,
                        availableUniforms: uniformNames,
                        comboValues: comboValues
                    )
                )
            } else {
                out.append("    [[maybe_unused]] \(varying.metalType) \(varying.name) = \(initializer);")
            }
        }

        for declaration in mutableGlobals {
            out.append("    [[maybe_unused]] \(declaration.metalType) \(declaration.name) = \(declaration.initializer);")
        }

        out.append(contentsOf: autoSwayReconstruction)

        out.append("    {")
        out.append(warningCleanMainBody)
        out.append("    }")
        out.append("}")
        return out.joined(separator: "\n")
    }

    private static let metalStdlibMacroDefinitions: Set<String> = [
        "M_PI_F"
    ]

    private static func neutralizeMetalStdlibMacroRedefinitions(_ source: String) -> String {
        guard source.contains("#") else { return source }
        return source.components(separatedBy: "\n").map { line in
            guard let macroName = defineMacroName(in: line),
                  metalStdlibMacroDefinitions.contains(macroName) else {
                return line
            }
            return "// disabled duplicate Metal stdlib macro definition: \(macroName)"
        }.joined(separator: "\n")
    }

    private static func defineMacroName(in line: String) -> String? {
        var trimmed = line.trimmingCharacters(in: .whitespaces)
        guard trimmed.first == "#" else { return nil }
        trimmed.removeFirst()

        let directive = trimmed.trimmingCharacters(in: .whitespaces)
        guard directive.hasPrefix("define") else { return nil }

        let afterDirective = directive.dropFirst("define".count)
        guard afterDirective.first?.isWhitespace == true else { return nil }
        let afterWhitespace = afterDirective.drop(while: { $0.isWhitespace })
        guard let first = afterWhitespace.first, isIdentifierStart(first) else { return nil }

        var name = ""
        for ch in afterWhitespace {
            guard isIdentifierCharacter(ch) else { break }
            name.append(ch)
        }
        return name
    }

    private static func appendCompatibilityPrelude(
        to out: inout [String],
        helpers: String,
        comboValues: [String: Int]
    ) {
        let existingFunctionNames = Set(parseHelperFunctions(in: helpers).map(\.name))

        if !existingFunctionNames.contains("mod") {
            out.append("inline float mod(float x, float y) { return x - y * floor(x / y); }")
            out.append("inline float mod(float x, int y) { return mod(x, float(y)); }")
            out.append("inline float2 mod(float2 x, float2 y) { return x - y * floor(x / y); }")
            out.append("inline float2 mod(float2 x, float y) { return mod(x, float2(y)); }")
            out.append("inline float2 mod(float2 x, int y) { return mod(x, float(y)); }")
            out.append("inline float3 mod(float3 x, float3 y) { return x - y * floor(x / y); }")
            out.append("inline float3 mod(float3 x, float y) { return mod(x, float3(y)); }")
            out.append("inline float3 mod(float3 x, int y) { return mod(x, float(y)); }")
            out.append("inline float4 mod(float4 x, float4 y) { return x - y * floor(x / y); }")
            out.append("inline float4 mod(float4 x, float y) { return mod(x, float4(y)); }")
            out.append("inline float4 mod(float4 x, int y) { return mod(x, float(y)); }")
        }

        if !existingFunctionNames.contains("greyscale") {
            out.append("inline float greyscale(float3 c) { return dot(c, float3(0.299, 0.587, 0.114)); }")
            out.append("inline float greyscale(float4 c) { return greyscale(c.rgb); }")
        }

        if !existingFunctionNames.contains("rgb2hsv") {
            out.append(
                """
                inline float3 rgb2hsv(float3 c) {
                    float4 K = float4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);
                    float4 p = mix(float4(c.bg, K.wz), float4(c.gb, K.xy), step(c.b, c.g));
                    float4 q = mix(float4(p.xyw, c.r), float4(c.r, p.yzx), step(p.x, c.r));
                    float d = q.x - min(q.w, q.y);
                    float e = 1.0e-10;
                    return float3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);
                }
                """
            )
        }

        if !existingFunctionNames.contains("hsv2rgb") {
            out.append(
                """
                inline float3 hsv2rgb(float3 c) {
                    float4 K = float4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);
                    float3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
                    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
                }
                """
            )
        }

        if !existingFunctionNames.contains("DecompressNormal") {
            let texture1Format = comboValues["TEX1FORMAT"]
                ?? WPEOfficialTextureFormatABI.rgba8888
            let assignmentSwizzle: String
            let packedChannels: String
            let packedBias: String
            if WPEOfficialTextureFormatABI.isCompressedNormalFormat(texture1Format) {
                assignmentSwizzle = ".yx"
                packedChannels = "packed.yw"
                packedBias = "float2(0.965, 1.0)"
            } else if texture1Format == WPEOfficialTextureFormatABI.rg88 {
                assignmentSwizzle = ""
                packedChannels = "packed.rg"
                packedBias = "float2(1.0)"
            } else {
                assignmentSwizzle = ""
                packedChannels = "packed.wy"
                packedBias = "float2(1.0)"
            }
            out.append(
                """
                inline float3 DecompressNormal(float4 packed) {
                    float2 nxy;
                    nxy\(assignmentSwizzle) = \(packedChannels) * 2.0 - \(packedBias);
                    float nz = sqrt(max(0.0, 1.0 - dot(nxy, nxy)));
                    return float3(nxy, nz);
                }
                """
            )
            out.append("inline float3 DecompressNormal(float3 packed) { return DecompressNormal(float4(packed, 0.0)); }")
        }

        out.append(
            """
            inline float wpe_safe_ratio(float numerator, float denominator) {
                return abs(denominator) > 0.000001 ? numerator / denominator : 0.0;
            }
            inline float2 wpe_rotate_vec2(float2 v, float angle) {
                float c = cos(angle);
                float s = sin(angle);
                return float2(c * v.x - s * v.y, s * v.x + c * v.y);
            }
            inline float2 wpe_safe_normalize(float2 v) {
                float len = length(v);
                return len > 1e-8 ? v / len : float2(0.0, 1.0);
            }
            inline float2 wpe_scroll_vector(float scrollX, float scrollY, float time) {
                float2 scroll = float2(scrollX, scrollY);
                return sign(scroll) * pow(abs(scroll), float2(2.0)) * time;
            }
            inline float4 wpe_texcoord_with_resolution(float2 uv, float4 resolution) {
                float2 scale = float2(
                    wpe_safe_ratio(resolution.z, resolution.x),
                    wpe_safe_ratio(resolution.w, resolution.y)
                );
                return float4(uv, uv * scale);
            }
            inline float4 wpe_texcoord_mask(float2 uv, float4 resolution) {
                float2 scale = float2(
                    wpe_safe_ratio(resolution.z, resolution.x),
                    wpe_safe_ratio(resolution.w, resolution.y)
                );
                return float4(uv * scale, scale);
            }
            // swing.vert / twirl.vert v_TexCoord: .z = the layer aspect (swing reads
            // g_Texture0Resolution.x/.y, twirl .z/.w), .w = sin(t·speed + phase·2π)·amount
            // — the time-driven swing/twirl phase. Deliberately absent from the
            // texCoordZWResolutionSlot family table (.zw packs aspect+phase, not a scaled
            // UV); the float4(in.uv, in.uv) default fed screen position into both, freezing
            // the animation into a position-dependent warp. Degenerate resolution falls
            // back to aspect 1 (not 0): both fragments divide by .z on the way out.
            inline float4 wpe_swing_texcoord(float2 uv, float2 resolution, float time, float speed, float phase, float amount) {
                float aspect = wpe_safe_ratio(resolution.x, resolution.y);
                return float4(uv, abs(aspect) > 0.000001 ? aspect : 1.0, sin(time * speed + phase * 6.28318530718) * amount);
            }
            inline float4 wpe_ripple_texcoord(float2 uv, float time, float animationSpeed, float scrollSpeed, float direction, float ratio, float scale, float4 texture0Resolution) {
                float animation = time * animationSpeed * animationSpeed;
                float2 scroll = wpe_rotate_vec2(float2(0.0, 1.0), direction) * scrollSpeed * scrollSpeed * time;
                float4 ripple = float4(uv + animation + scroll, uv * 1.333 - animation + scroll) * scale;
                ripple.xz *= wpe_safe_ratio(texture0Resolution.x, texture0Resolution.y);
                ripple.yw *= ratio;
                return ripple;
            }
            inline float2 wpe_iris_texcoord(float timeUniform, float speed, float phaseOffset, float rough, float noiseAmount, float2 scale) {
                float time = timeUniform * speed + phaseOffset;
                float lowDt = floor(time);
                float2 motion2 = sin(1.9 * (lowDt + float2(0.0, 1.0)));
                float4 motion4 = sin(2.5 * (lowDt + float4(0.0, 0.0, 1.0, 1.0)) + float4(1.0, 2.0, 1.0, 2.0));
                float2 moveStart = motion2.xx + motion4.xy;
                float2 moveEnd = motion2.yy + motion4.zw;
                float eased = wpe_smoothstep(1.0 - rough, 1.0, cos(fract(time) * 3.14159265359) * -0.5 + 0.5);
                float2 da = mix(moveStart, moveEnd, eased);
                da.x += sin(time) * noiseAmount;
                da.y += cos(time) * noiseAmount;
                return da * scale * 0.001;
            }
            inline float wpe_foliage_aspect(float4 texture0Resolution, float ratio) {
                float aspect = wpe_safe_ratio(texture0Resolution.z, texture0Resolution.w) * ratio;
                return abs(aspect) > 0.000001 ? aspect : 1.0;
            }
            inline float4 wpe_foliage_texcoord_noise(float2 uv, float noiseScale, float ratio, float direction, float4 texture0Resolution) {
                float aspect = wpe_foliage_aspect(texture0Resolution, ratio);
                return float4(uv * noiseScale, wpe_rotate_vec2(float2(1.0 / aspect, aspect), direction));
            }
            inline float3 wpe_foliage_params(float2 uv, float direction, float strength) {
                return float3(wpe_rotate_vec2(uv, direction), strength * strength * 0.005);
            }
            // filmgrain.vert's v_TexCoordNoise: two noise lookups scrolled by frac(time)
            // and tiled by g_NoiseScale (aspect-corrected on x). Distinct from the foliage
            // variant above — without it the varying fell back to raw uv, sampling the
            // 256² noise once across the whole frame (smooth blotches soft-light blended
            // over everything = a static "retro filter") instead of fine animated grain.
            inline float4 wpe_filmgrain_texcoord_noise(float2 uv, float time, float scale, float4 texture0Resolution) {
                float t = fract(time);
                float aspect = wpe_safe_ratio(texture0Resolution.z, texture0Resolution.w);
                float4 coords = float4((uv + t) * scale, (uv - t * 2.5) * scale * 0.52);
                return coords * float4(aspect, 1.0, aspect, 1.0);
            }
            inline float2 wpe_bounds_vector(float2 bounds) {
                return float2(bounds.x, 1.0 / max(bounds.y - bounds.x, 0.000001));
            }
            // pulse.vert's non-audio `v_Pulse`: a time-driven sine gated through
            // g_PulseThresholds, scaled by g_PulseAmount (0 at rest, pulses over time).
            // Without it the float varying defaulted to `in.uv.x` — a left-to-right
            // brightness/alpha ramp instead of a uniform full-screen pulse.
            inline float wpe_pulse_response(float time, float2 thresholds, float speed, float phase, float amount) {
                float wave = sin(time * speed + (phase - 0.25) * 6.28318530717958647692) * 0.5 + 0.5;
                return wpe_smoothstep(thresholds.x, thresholds.y, wave) * amount;
            }
            // Vertex-stage `v_AudioShift` (WPE common.h CreateAudioResponse): the
            // FFT bins in [freqMin, freqMax] are averaged, smoothstepped against
            // g_AudioBounds, raised to g_AudioPower and scaled by g_AudioMultiply.
            // `mode` is the AUDIOPROCESSING combo (1=left, 2=right, 3=both). Returns
            // 0 when silent — matching WPE, where the effect rests until audio plays.
            // The fragment-only transpile has no vertex stage, so without this the
            // varying defaulted to `in.uv.x`, smearing the whole frame (chromatic
            // aberration / hue_shift glitch across the screen even with no audio).
            inline float wpe_audio_response16(
                thread const float (&left)[16],
                thread const float (&right)[16],
                int mode, float freqMin, float freqMax,
                float2 bounds, float power, float multiply
            ) {
                int lo = clamp(int(freqMin), 0, 15);
                int hi = clamp(int(freqMax), 0, 15);
                float response = 0.0;
                for (int a = lo; a <= hi; ++a) {
                    if (mode == 2) { response += right[a]; }
                    else if (mode == 3) { response += left[a] + right[a]; }
                    else { response += left[a]; }
                }
                float denom = max(freqMax - freqMin + 1.0, 1.0);
                if (mode == 3) { denom *= 2.0; }
                response /= denom;
                response = wpe_smoothstep(bounds.x, bounds.y, response);
                return clamp(pow(response, power), 0.0, 1.0) * multiply;
            }
            inline float wpe_audio_oscilloscope_value(
                float left, float right, int index, int resolution,
                int equalize, float lrBalance, float freqBalanceUniform, float ampExponent
            ) {
                float leftBalance = equalize != 0 ? (1.0 - lrBalance) * 0.5 : 0.5;
                float rightBalance = equalize != 0 ? (lrBalance + 1.0) * 0.5 : 0.5;
                float normalizedFrequency = float(index) / max(float(resolution), 1.0);
                float freqBalance = 1.0;
                if (equalize != 0) {
                    float bassBalance = (1.0 - freqBalanceUniform) * (1.0 - normalizedFrequency);
                    float trebleBalance = freqBalanceUniform * normalizedFrequency;
                    freqBalance = mix(bassBalance, trebleBalance, normalizedFrequency) * 2.5;
                }
                float amplitude = left * leftBalance + right * rightBalance;
                return pow(max(freqBalance * (amplitude + amplitude), 0.0), ampExponent + 0.01);
            }
            inline float4 wpe_waterflow_cycles(float time, float speed) {
                float t = time * speed;
                float4 cycles = float4(fract(t), fract(t + 0.5), fract(0.25 + t), fract(0.25 + t + 0.5));
                return cycles - float4(0.5);
            }
            inline float2 wpe_waterflow_blend(float time, float speed, float feather) {
                float t = time * speed;
                float bx = 2.0 * abs(fract(t) - 0.5);
                float bz = 2.0 * abs(fract(0.25 + t) - 0.5);
                float lo = 0.5 - feather, hi = 0.5 + feather;
                return float2(wpe_smoothstep(lo, hi, bx), wpe_smoothstep(lo, hi, bz));
            }
            inline float3x3 wpe_square_to_quad(float2 p0, float2 p1, float2 p2, float2 p3) {
                float dx0 = p0.x, dy0 = p0.y;
                float dx1 = p1.x, dy1 = p1.y;
                float dx2 = p3.x, dy2 = p3.y;
                float dx3 = p2.x, dy3 = p2.y;
                float diffx1 = dx1 - dx3;
                float diffy1 = dy1 - dy3;
                float diffx2 = dx2 - dx3;
                float diffy2 = dy2 - dy3;
                float det = diffx1 * diffy2 - diffx2 * diffy1;
                float sumx = dx0 - dx1 + dx3 - dx2;
                float sumy = dy0 - dy1 + dy3 - dy2;
                if (det == 0.0 || (sumx == 0.0 && sumy == 0.0)) {
                    return float3x3(
                        float3(dx1 - dx0, dy1 - dy0, 0.0),
                        float3(dx3 - dx1, dy3 - dy1, 0.0),
                        float3(dx0, dy0, 1.0)
                    );
                }
                float ovdet = 1.0 / det;
                float g = (sumx * diffy2 - diffx2 * sumy) * ovdet;
                float h = (diffx1 * sumy - sumx * diffy1) * ovdet;
                return float3x3(
                    float3(dx1 - dx0 + g * dx1, dy1 - dy0 + g * dy1, g),
                    float3(dx2 - dx0 + h * dx2, dy2 - dy0 + h * dy2, h),
                    float3(dx0, dy0, 1.0)
                );
            }
            inline float3x3 wpe_mat3_inverse(float3x3 m) {
                float a00 = m[0][0], a01 = m[0][1], a02 = m[0][2];
                float a10 = m[1][0], a11 = m[1][1], a12 = m[1][2];
                float a20 = m[2][0], a21 = m[2][1], a22 = m[2][2];
                float b01 = a22 * a11 - a12 * a21;
                float b11 = -a22 * a10 + a12 * a20;
                float b21 = a21 * a10 - a11 * a20;
                float det = a00 * b01 + a01 * b11 + a02 * b21;
                float invdet = abs(det) > 0.000001 ? 1.0 / det : 0.0;
                return float3x3(
                    float3(b01, -a22 * a01 + a02 * a21, a12 * a01 - a02 * a11) * invdet,
                    float3(b11, a22 * a00 - a02 * a20, -a12 * a00 + a02 * a10) * invdet,
                    float3(b21, -a21 * a00 + a01 * a20, a11 * a00 - a01 * a10) * invdet
                );
            }
            inline float3 wpe_perspective_texcoord(float2 uv, float2 p0, float2 p1, float2 p2, float2 p3) {
                // WPE: mul(vec3(uv,1), inverse(squareToQuad(...))); WPE mul(x,y) == y * x.
                return wpe_mat3_inverse(wpe_square_to_quad(p0, p1, p2, p3)) * float3(uv, 1.0);
            }
            // reflection.vert (PERSPECTIVE=0) v_ReflectedCoord: mirror uv across the
            // horizontal centre (offset shifts the mirror line), then rotate by
            // g_Direction. Transcribed verbatim — no V flip — because our fullscreen
            // in.uv already matches WPE a_TexCoord (both top-left, uv.y==0 at the top;
            // see WPEMetalBuiltins wpe_fullscreen_vertex). Without it the varying fell
            // back to raw in.uv, so the reflected sample == albedo (a no-op) and water
            // showed its flat base colour instead of the mirrored sky (scene 3413921910
            // rendered a solid pink band across the whole water surface).
            inline float2 wpe_reflection_texcoord(float2 uv, float direction, float offset) {
                float2 center = float2(0.5, 0.5);
                float2 delta = uv - center;
                delta.y += offset;
                delta.y = -delta.y;
                delta = wpe_rotate_vec2(delta, direction);
                return center + delta;
            }
            """
        )
    }

    private static func varyingInitializer(
        for varying: WPEVaryingDecl,
        shaderName: String,
        availableUniforms: Set<String>,
        comboValues: [String: Int] = [:]
    ) -> String {
        // multistage_wave: v_DirectionN = normalize(g_SpinCenter(N+1) - g_SpinCenterN),
        // declared vec4 (.zw = the direction rotated by g_DirectionOffset) under
        // GLOBAL_ROTATION, else vec2. Gated on the per-node g_SpinCenter uniforms so it
        // never intercepts the dualwaves `v_Direction2` case below (which has none).
        if ["float2", "float4"].contains(varying.metalType),
           varying.name.hasPrefix("v_Direction"),
           let nodeIndex = Int(varying.name.dropFirst("v_Direction".count)),
           nodeIndex >= 1, nodeIndex <= 10,
           hasUniforms("g_SpinCenter\(nodeIndex)", "g_SpinCenter\(nodeIndex + 1)", in: availableUniforms) {
            let raw = "wpe_safe_normalize(g_SpinCenter\(nodeIndex + 1) - g_SpinCenter\(nodeIndex))"
            if varying.metalType == "float4" {
                // .zw carries the g_DirectionOffset-rotated direction only under GLOBAL_ROTATION.
                let rotated = comboValues["GLOBAL_ROTATION"] == 1 && availableUniforms.contains("g_DirectionOffset")
                    ? "wpe_rotate_vec2(\(raw), g_DirectionOffset)"
                    : raw
                return "float4(\(raw), \(rotated))"
            }
            return raw
        }
        switch varying.name {
        case "v_TexCoord":
            if varying.metalType == "float2" {
                return "in.uv"
            }
            // swing/twirl pack aspect + sine phase into .zw; rebuild the exact .vert
            // formula before the resolution-scaled-UV path (whose MASK ladder would
            // otherwise mis-fill .zw with a scaled UV). Only the resolution components
            // differ: swing reads .x/.y, twirl .z/.w.
            if varying.metalType == "float4",
               let family = texCoordZWFamilyName(shaderName: shaderName),
               family == "swing" || family == "twirl",
               hasUniforms("g_Time", "g_Speed", "g_Phase", "g_Amount", "g_Texture0Resolution", in: availableUniforms) {
                let components = family == "swing" ? "xy" : "zw"
                return "wpe_swing_texcoord(in.uv, g_Texture0Resolution.\(components), g_Time, g_Speed, g_Phase, g_Amount)"
            }
            // blur_precise_gaussian.vert:29-33 — `.zw` is the single-axis per-tap step
            // (`VERTICAL ? (0, g_Scale.y/res.w) : (g_Scale.x/res.z, 0)`), NOT a scaled UV, so it
            // must come before the resolution ladder below. The float4(uv,uv) default made the
            // step a full screen UV and blur13a averaged the entire frame.
            if varying.metalType == "float4",
               texCoordZWFamilyName(shaderName: shaderName) == "blur_precise_gaussian",
               hasUniforms("g_Scale", "g_Texture0Resolution", in: availableUniforms) {
                return comboValues["VERTICAL"] == 1
                    ? "float4(in.uv, 0.0, g_Scale.y / g_Texture0Resolution.w)"
                    : "float4(in.uv, g_Scale.x / g_Texture0Resolution.z, 0.0)"
            }
            if varying.metalType == "float4",
               let resolutionUniform = texCoordResolutionUniform(
                shaderName: shaderName,
                availableUniforms: availableUniforms,
                comboValues: comboValues
               ) {
                return "wpe_texcoord_with_resolution(in.uv, \(resolutionUniform))"
            }
        case "v_TexCoordMask":
            if varying.metalType == "float4",
               availableUniforms.contains("g_Texture3Resolution") {
                return "wpe_texcoord_mask(in.uv, g_Texture3Resolution)"
            }
            // blur_precise_gaussian.vert:37 scales the mask UV by slot 2's image/padded ratio;
            // the float2 default left it as raw screen UV. Deliberately family-gated: across the
            // corpus a float2 `v_TexCoordMask` reads slot 1, 2 OR 3 depending on the effect
            // (blur_radial_gaussian, border_preprocessing_gaussian, depthparallax, spin, swing,
            // twirl all declare it too), and binding the wrong texture's resolution is worse than
            // the raw-UV fallback those families have today.
            if varying.metalType == "float2",
               texCoordZWFamilyName(shaderName: shaderName) == "blur_precise_gaussian",
               availableUniforms.contains("g_Texture2Resolution") {
                return "wpe_texcoord_mask(in.uv, g_Texture2Resolution).xy"
            }
        case "v_TexCoordLeftTop":
            // fluidsimulation_*.vert: LeftTop = uv.xyxy, then .x -= texel.x,
            // .w += texel.y (texel = 1/g_Texture0Resolution.xy). All five
            // family .verts compute the identical formula. The screen-UV
            // fallback collapsed the neighbour taps onto one texel, zeroing
            // divergence/curl — the simulation froze entirely.
            if varying.metalType == "float4",
               availableUniforms.contains("g_Texture0Resolution") {
                return "float4(in.uv.x - 1.0 / g_Texture0Resolution.x, in.uv.y, in.uv.x, in.uv.y + 1.0 / g_Texture0Resolution.y)"
            }
        case "v_TexCoordRightBottom":
            // Mirror of v_TexCoordLeftTop: .x += texel.x, .w -= texel.y.
            if varying.metalType == "float4",
               availableUniforms.contains("g_Texture0Resolution") {
                return "float4(in.uv.x + 1.0 / g_Texture0Resolution.x, in.uv.y, in.uv.x, in.uv.y - 1.0 / g_Texture0Resolution.y)"
            }
        case "v_StepSize":
            // apply.vert:14 / up_sample.vert:13 (workshop 2822917890 bloom family):
            // `1.0 / vec4(-g_Texture0Resolution.xy, g_Texture0Resolution.xy)`, the
            // per-texel step for the box-blur's 4 diagonal taps. The float4(uv,uv)
            // default fed screen position in as a sample offset (3554161528 sky).
            if varying.metalType == "float4",
               availableUniforms.contains("g_Texture0Resolution") {
                return "1.0 / float4(-g_Texture0Resolution.xy, g_Texture0Resolution.xy)"
            }
        case "v_SizeMultiplier":
            // blur_gaussian.vert:30 (same bloom family):
            // `vec2(aRatio, 1.0) * (u_radius + u_radius) * iterations * g_TexelSize`
            // where aRatio = u_ratio under ANAMORPHIC else 1.0, and iterations =
            // 0.675 under HIGH_QUALITY else 1.5 (compile-time #if, folded here).
            // The in.uv default made the blur offset grow with screen position.
            // `g_TexelSize` is now packed from the SCENE resolution
            // (`WPEMetalRenderExecutor.texelSizeValue`), so use it directly.
            // It used to be substituted with 1/g_Texture0Resolution.xy on the
            // premise that "the blur input is a same-size framebuffer"; RenderDoc
            // disproved that — WPE holds g_TexelSize at 1/(3840,2160) for every
            // pass of a chain that runs down to 240x135, so the substitution was
            // 2x/4x/8x/16x too wide as the chain descended.
            if varying.metalType == "float2",
               hasUniforms("g_TexelSize", "u_radius", in: availableUniforms) {
                let aRatio = comboValues["ANAMORPHIC"] == 1 && availableUniforms.contains("u_ratio")
                    ? "u_ratio" : "1.0"
                let iterations = comboValues["HIGH_QUALITY"] == 1 ? "0.675" : "1.5"
                return "float2(\(aRatio), 1.0) * (u_radius + u_radius) * \(iterations) * g_TexelSize"
            }
        case "v_Scroll":
            if varying.metalType == "float2",
               hasUniforms("g_ScrollX", "g_ScrollY", "g_Time", in: availableUniforms) {
                return "wpe_scroll_vector(g_ScrollX, g_ScrollY, g_Time)"
            }
        case "v_Direction":
            if varying.metalType == "float2",
               availableUniforms.contains("g_Direction") {
                return "wpe_rotate_vec2(float2(0.0, 1.0), g_Direction)"
            }
        case "v_Direction2":
            // DUALWAVES second wave direction: rotateVec2((0,1), g_Direction2).
            if varying.metalType == "float2",
               availableUniforms.contains("g_Direction2") {
                return "wpe_rotate_vec2(float2(0.0, 1.0), g_Direction2)"
            }
        case "v_ReflectedCoord":
            // reflection.vert PERSPECTIVE=0: vertical mirror (+ offset) rotated by
            // g_Direction. The PERSPECTIVE=1 branch uses v_TexCoordPerspective instead,
            // already handled below. Falling through to raw in.uv makes the reflected
            // sample identical to albedo (no reflection) — flat water.
            if varying.metalType == "float2",
               hasUniforms("g_Direction", "g_ReflectionOffset", in: availableUniforms) {
                return "wpe_reflection_texcoord(in.uv, g_Direction, g_ReflectionOffset)"
            }
        case "v_TexCoordPerspective", "v_TexCoordFx":
            // PERSPECTIVE / lightshafts: mul(vec3(uv,1), inverse(squareToQuad(g_Point0..3))),
            // matching WPE common_perspective.h byte-for-byte. lightshafts.vert
            // computes `v_TexCoordFx` identically and the fragment does its own
            // `.xy/.z` perspective divide, so the raw homogeneous float3 is correct.
            if varying.metalType == "float3",
               hasUniforms("g_Point0", "g_Point1", "g_Point2", "g_Point3", in: availableUniforms) {
                return "wpe_perspective_texcoord(in.uv, g_Point0, g_Point1, g_Point2, g_Point3)"
            }
            if varying.metalType == "float3" {
                return "float3(in.uv, 1.0)"
            }
        case "v_PerspCoord":
            // audio_responsive_oscilloscope.vert only applies squareToQuad under
            // PERSPECTIVE=1; default PERSPECTIVE=0 is the raw texture coordinate
            // with homogeneous z=1. Using the perspective path unconditionally can
            // make the linear waveform clamp out and leave an opaque solid layer.
            if varying.metalType == "float3" {
                if comboValues["PERSPECTIVE"] == 1,
                   hasUniforms("g_Point0", "g_Point1", "g_Point2", "g_Point3", in: availableUniforms) {
                    return "wpe_perspective_texcoord(in.uv, g_Point0, g_Point1, g_Point2, g_Point3)"
                }
                return "float3(in.uv, 1.0)"
            }
        case "v_ViewCoord":
            // Effects that sample the current full-frame buffer often use
            // `v_ViewCoord.xy / v_ViewCoord.z * 0.5 + 0.5`. Preserve a valid
            // homogeneous z and map back to the current quad UV as a conservative
            // fragment-side reconstruction.
            if varying.metalType == "float3" {
                return "float3(in.uv * 2.0 - 1.0, 1.0)"
            }
        case "audioValue":
            if varying.metalType == "float4" {
                return "float4(0.0)"
            }
        case "v_TexCoordRipple":
            if varying.metalType == "float4",
               hasUniforms(
                "g_Time",
                "g_AnimationSpeed",
                "g_ScrollSpeed",
                "g_Direction",
                "g_Ratio",
                "g_Scale",
                "g_Texture0Resolution",
                in: availableUniforms
               ) {
                return "wpe_ripple_texcoord(in.uv, g_Time, g_AnimationSpeed, g_ScrollSpeed, g_Direction, g_Ratio, g_Scale, g_Texture0Resolution)"
            }
        case "v_TexCoordIris":
            if varying.metalType == "float2",
               hasUniforms(
                "g_Time",
                "g_Speed",
                "g_PhaseOffset",
                "g_Rough",
                "g_NoiseAmount",
                "g_Scale",
                in: availableUniforms
               ) {
                return "wpe_iris_texcoord(g_Time, g_Speed, g_PhaseOffset, g_Rough, g_NoiseAmount, g_Scale)"
            }
        case "v_TexCoordNoise":
            // foliage variant: tiled noise rotated by g_Direction (needs g_Ratio too).
            if varying.metalType == "float4",
               hasUniforms(
                "g_NoiseScale",
                "g_Ratio",
                "g_Direction",
                "g_Texture0Resolution",
                in: availableUniforms
               ) {
                return "wpe_foliage_texcoord_noise(in.uv, g_NoiseScale, g_Ratio, g_Direction, g_Texture0Resolution)"
            }
            // filmgrain variant: two frac(time)-scrolled, g_NoiseScale-tiled lookups.
            // No g_Ratio/g_Direction, so it can't reuse the foliage helper; without this
            // it fell through to raw uv and stretched the noise once across the frame.
            if varying.metalType == "float4",
               hasUniforms("g_NoiseScale", "g_Time", "g_Texture0Resolution", in: availableUniforms) {
                return "wpe_filmgrain_texcoord_noise(in.uv, g_Time, g_NoiseScale, g_Texture0Resolution)"
            }
        case "v_Params":
            if varying.metalType == "float3",
               hasUniforms("g_Direction", "g_Strength", in: availableUniforms) {
                return "wpe_foliage_params(in.uv, g_Direction, g_Strength)"
            }
        case "v_equalScaleFactor":
            // multistage_wave.vert: aspect-correction factor (≥1 per axis), NOT screen UV.
            // Defaulting to in.uv stretched the wave field horizontally across the frame.
            if varying.metalType == "float2",
               availableUniforms.contains("g_Texture0Resolution") {
                return "float2(max(1.0, wpe_safe_ratio(g_Texture0Resolution.x, g_Texture0Resolution.y)), max(1.0, wpe_safe_ratio(g_Texture0Resolution.y, g_Texture0Resolution.x)))"
            }
        case "v_Pulse":
            // pulse.vert: AUDIOPROCESSING → CreateAudioResponse (0 when silent); else a
            // time-driven sine pulse. The float varying used to default to in.uv.x — a
            // left-to-right ramp instead of a uniform full-screen pulse.
            if varying.metalType == "float" {
                let mode = comboValues["AUDIOPROCESSING"] ?? 0
                if mode != 0,
                   hasUniforms(
                    "g_AudioSpectrum16Left", "g_AudioSpectrum16Right",
                    "g_AudioFrequencyMin", "g_AudioFrequencyMax",
                    "g_AudioBounds", "g_AudioPower", "g_AudioMultiply",
                    in: availableUniforms
                   ) {
                    return "wpe_audio_response16(g_AudioSpectrum16Left, g_AudioSpectrum16Right, \(mode), g_AudioFrequencyMin, g_AudioFrequencyMax, g_AudioBounds, g_AudioPower, g_AudioMultiply)"
                }
                if hasUniforms("g_Time", "g_PulseThresholds", "g_PulseSpeed", "g_PulsePhase", "g_PulseAmount", in: availableUniforms) {
                    return "wpe_pulse_response(g_Time, g_PulseThresholds, g_PulseSpeed, g_PulsePhase, g_PulseAmount)"
                }
                return "0.0"
            }
        case "v_ParallaxOffset":
            // depthparallax.vert: pointer-projected offset, ·0.5+0.5. The full form needs
            // g_EffectTextureProjectionMatrixInverse (a mat uniform excluded from fragment
            // injection), so use the vert's own simplified equivalent (= g_ParallaxPosition):
            // neutral (0.5) when the pointer is centered, instead of the in.uv ramp that
            // warped the parallax sample across the screen.
            if varying.metalType == "float2" {
                return availableUniforms.contains("g_ParallaxPosition") ? "g_ParallaxPosition" : "float2(0.5)"
            }
        case "v_Bounds":
            if varying.metalType == "float2",
               availableUniforms.contains("g_Bounds") {
                return "wpe_bounds_vector(g_Bounds)"
            }
        case "v_Cycles":
            // waterflow.vert: four scroll-loop phases (frac(t·speed)+offsets) − 0.5,
            // bounded to ±0.5 so the flow displacement oscillates instead of growing
            // with screen position (the default float4(uv,uv) caused the smear band).
            if varying.metalType == "float4",
               hasUniforms("g_Time", "g_FlowSpeed", in: availableUniforms) {
                return "wpe_waterflow_cycles(g_Time, g_FlowSpeed)"
            }
        case "v_Blend":
            // waterflow.vert: smoothstep cross-fade weights between the two phase samples.
            if varying.metalType == "float2",
               hasUniforms("g_Time", "g_FlowSpeed", "g_PhaseFeather", in: availableUniforms) {
                return "wpe_waterflow_blend(g_Time, g_FlowSpeed, g_PhaseFeather)"
            }
        case "v_AudioShift":
            // Audio-reactive scalar computed in the vertex stage (CreateAudioResponse).
            // Reconstruct it from the spectrum + audio uniforms so it rests at 0 when
            // silent instead of falling through to the `in.uv.x` float default, which
            // smeared chromatic_aberration / hue_shift across the whole frame.
            if varying.metalType == "float",
               hasUniforms(
                "g_AudioSpectrum16Left",
                "g_AudioSpectrum16Right",
                "g_AudioFrequencyMin",
                "g_AudioFrequencyMax",
                "g_AudioBounds",
                "g_AudioPower",
                "g_AudioMultiply",
                in: availableUniforms
               ) {
                let mode = comboValues["AUDIOPROCESSING"] ?? 1
                return "wpe_audio_response16(g_AudioSpectrum16Left, g_AudioSpectrum16Right, \(mode), g_AudioFrequencyMin, g_AudioFrequencyMax, g_AudioBounds, g_AudioPower, g_AudioMultiply)"
            }
            return "0.0"
        case "v_AudioPulse":
            // Audio-reactive pulse (CreateAudioResponse): 0 when silent, like v_AudioShift.
            // Reconstruct the real response when the spectrum uniforms are present so the
            // effect reacts to audio instead of staying flat; falls back to 0 otherwise.
            if varying.metalType == "float" {
                let mode = comboValues["AUDIOPROCESSING"] ?? 1
                if hasUniforms(
                    "g_AudioSpectrum16Left", "g_AudioSpectrum16Right",
                    "g_AudioFrequencyMin", "g_AudioFrequencyMax",
                    "g_AudioBounds", "g_AudioPower", "g_AudioMultiply",
                    in: availableUniforms
                ) {
                    return "wpe_audio_response16(g_AudioSpectrum16Left, g_AudioSpectrum16Right, \(mode), g_AudioFrequencyMin, g_AudioFrequencyMax, g_AudioBounds, g_AudioPower, g_AudioMultiply)"
                }
                return "0.0"
            }
        default:
            break
        }

        switch varying.metalType {
        case "float2":
            return "in.uv"
        case "float3":
            return "float3(in.uv, 0.0)"
        case "float4":
            return "float4(in.uv, in.uv)"
        case "float":
            return "in.uv.x"
        default:
            return "\(varying.metalType)(0)"
        }
    }

    /// down_sample.vert:12-15 / light_map.vert:15-18 (workshop 2822917890 bloom
    /// family): both compute the same 4-tap diagonal box filter around a_TexCoord,
    /// `offsets = 1.0 / g_Texture0Resolution.xy`. The generic array path below
    /// calls `varyingInitializer` ONCE and repeats that single value across all N
    /// slots, collapsing the box filter to a single point sample (3554161528 sky).
    /// Matched on varying name + array shape, not shader name, so other bloom/glow
    /// packages sharing this exact offsets convention reconstruct too.
    private static func texCoordBoxFilterInitializers(
        varying: WPEVaryingDecl,
        availableUniforms: Set<String>
    ) -> [String]? {
        guard varying.name == "v_TexCoord",
              varying.metalType == "float2",
              varying.arrayLength == 4,
              availableUniforms.contains("g_Texture0Resolution") else {
            return nil
        }
        return [
            "in.uv - (1.0 / g_Texture0Resolution.xy)",
            "in.uv + float2(1.0 / g_Texture0Resolution.x, -1.0 / g_Texture0Resolution.y)",
            "in.uv + float2(-1.0 / g_Texture0Resolution.x, 1.0 / g_Texture0Resolution.y)",
            "in.uv + (1.0 / g_Texture0Resolution.xy)",
        ]
    }

    private static func symbolicArrayReconstructionLines(
        for varying: WPEVaryingDecl,
        availableUniforms: Set<String>,
        comboValues: [String: Int]
    ) -> [String] {
        guard varying.name == "audioValue",
              varying.metalType == "float4" else {
            return []
        }

        let resolution = comboValues["RESOLUTION"] ?? 32
        let leftName: String
        let rightName: String
        switch resolution {
        case 16:
            leftName = "g_AudioSpectrum16Left"
            rightName = "g_AudioSpectrum16Right"
        case 64:
            leftName = "g_AudioSpectrum64Left"
            rightName = "g_AudioSpectrum64Right"
        default:
            leftName = "g_AudioSpectrum32Left"
            rightName = "g_AudioSpectrum32Right"
        }

        guard hasUniforms(leftName, rightName, "u_ampExponent", "u_FreqBalance", "u_LRBalance", in: availableUniforms) else {
            return []
        }

        let equalize = comboValues["EQUALIZE"] ?? 0
        return [
            "    for (int wpeAudioIndex = 0; wpeAudioIndex < \(resolution); wpeAudioIndex += 4) {",
            "        \(varying.name)[wpeAudioIndex / 4] = float4(",
            "            wpe_audio_oscilloscope_value(\(leftName)[wpeAudioIndex + 0], \(rightName)[wpeAudioIndex + 0], wpeAudioIndex + 0, \(resolution), \(equalize), u_LRBalance, u_FreqBalance, u_ampExponent),",
            "            wpe_audio_oscilloscope_value(\(leftName)[wpeAudioIndex + 1], \(rightName)[wpeAudioIndex + 1], wpeAudioIndex + 1, \(resolution), \(equalize), u_LRBalance, u_FreqBalance, u_ampExponent),",
            "            wpe_audio_oscilloscope_value(\(leftName)[wpeAudioIndex + 2], \(rightName)[wpeAudioIndex + 2], wpeAudioIndex + 2, \(resolution), \(equalize), u_LRBalance, u_FreqBalance, u_ampExponent),",
            "            wpe_audio_oscilloscope_value(\(leftName)[wpeAudioIndex + 3], \(rightName)[wpeAudioIndex + 3], wpeAudioIndex + 3, \(resolution), \(equalize), u_LRBalance, u_FreqBalance, u_ampExponent)",
            "        );",
            "    }"
        ]
    }

    static func hasUniforms(_ names: String..., in availableUniforms: Set<String>) -> Bool {
        names.allSatisfy { availableUniforms.contains($0) }
    }

    private static func texCoordResolutionUniform(
        shaderName: String,
        availableUniforms: Set<String>,
        comboValues: [String: Int] = [:]
    ) -> String? {
        let lowercased = shaderName.lowercased()
        // Families with a verified .vert use its exact resolution slot: the mask/aux
        // texture is NOT always g_Texture1 (vhs/filmgrain/nitro/waterripple/clouds/
        // pulse/motionblur bind it at slot 2, lightshafts at slot 3), and the generic
        // MASK→T1 ladder below mis-scaled those.
        if let slot = texCoordZWResolutionSlot(shaderName: shaderName, comboValues: comboValues) {
            // No falling through to the generic ladder for a recognized family: with the
            // exact slot's resolution missing (malformed input), the ladder would scale
            // .zw by a DIFFERENT texture's aspect while the .zw sample stays preserved.
            // nil leaves .zw = uv — identical to the historical .xy downgrade.
            let uniform = "g_Texture\(slot)Resolution"
            return availableUniforms.contains(uniform) ? uniform : nil
        }
        // WPE distortion shaders (waterwaves/waterripple/foliagesway…) scale
        // `v_TexCoord.zw` by the *active auxiliary texture's* resolution,
        // mirroring the `#if MASK / #elif TIMEOFFSET` ladder in the .vert:
        // MASK uses the opacity-mask texture (g_Texture1), TIMEOFFSET uses the
        // time-offset texture (g_Texture2). The previous combo-blind heuristic
        // always picked g_Texture1Resolution, mis-scaling the TIMEOFFSET case.
        if comboValues["MASK"] == 1, availableUniforms.contains("g_Texture1Resolution") {
            return "g_Texture1Resolution"
        }
        if comboValues["TIMEOFFSET"] == 1, availableUniforms.contains("g_Texture2Resolution") {
            return "g_Texture2Resolution"
        }
        if lowercased.contains("pulse"), availableUniforms.contains("g_Texture2Resolution") {
            return "g_Texture2Resolution"
        }
        if availableUniforms.contains("g_Texture1Resolution") {
            return "g_Texture1Resolution"
        }
        if availableUniforms.contains("g_Texture2Resolution") {
            return "g_Texture2Resolution"
        }
        return nil
    }

    /// Map `g_Texture0` / `g_Texture1` etc. to a slot index by parsing the trailing digit.
    static func textureSlot(for name: String) -> Int? {
        let prefix = "g_Texture"
        guard name.hasPrefix(prefix) else { return nil }
        return Int(name.dropFirst(prefix.count))
    }
}
#endif
