import Foundation

/// Shared contract between the main app (writer) and the wallpaper appex
/// (reader). Compiled into both targets — keep it Foundation-only.
///
/// On-disk layout, inside the *host app's* sandbox container:
///   .../Library/Application Support/Loomscreen/SystemWallpaper/
///     manifest.json      written by the app
///     heartbeat.json     written back by the appex (plan §3 U5)
///     Videos/<fileName>  copied video assets
/// What the wallpaper does once the desktop is showing. The lock screen always
/// plays: that is the one moment the system asks for motion.
enum SystemWallpaperPlaybackMode: String, Codable, Equatable, CaseIterable {
    /// Keep playing on the desktop too.
    case always
    /// Ease to a still after unlocking, the way Apple's own video wallpapers do.
    case stillOnDesktop
}

struct SystemWallpaperManifest: Codable, Equatable {
    struct Item: Codable, Equatable, Identifiable {
        var id: String
        var title: String
        var fileName: String
        /// JPEG next to the video, generated by the app at publish time — the
        /// system settings panel wants a thumbnail *file URL* (contract §1.3).
        var thumbnailFileName: String?
        var addedAt: Date
    }

    var version: Int
    var items: [Item]
    var playbackMode: SystemWallpaperPlaybackMode

    static let currentVersion = 1
    static let empty = SystemWallpaperManifest(
        version: currentVersion,
        items: [],
        playbackMode: .always
    )

    init(version: Int, items: [Item], playbackMode: SystemWallpaperPlaybackMode = .always) {
        self.version = version
        self.items = items
        self.playbackMode = playbackMode
    }

    private enum CodingKeys: String, CodingKey { case version, items, playbackMode }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        version = try c.decode(Int.self, forKey: .version)
        // File names are used verbatim under Videos/ by both processes,
        // including for deletion — a manifest edited to carry "../" must not
        // become a path that escapes the directory. Dropping the item (rather
        // than failing the whole manifest) keeps the rest of the library alive.
        items = try c.decode([Item].self, forKey: .items).filter { item in
            Self.isSafeFileName(item.fileName)
                && item.thumbnailFileName.map(Self.isSafeFileName) != false
        }
        // Manifests written before the switch existed kept playing on the
        // desktop, so that stays their behaviour after an update.
        playbackMode = try c.decodeIfPresent(SystemWallpaperPlaybackMode.self, forKey: .playbackMode) ?? .always
    }

    /// A single path component: no separators, no traversal, not empty.
    static func isSafeFileName(_ name: String) -> Bool {
        !name.isEmpty && !name.contains("/") && !name.contains("\0")
            && name != "." && name != ".."
    }
}

/// Written by the appex whenever the system drives it, so the sandboxed app
/// can infer "in use" without pluginkit (which it cannot exec).
struct SystemWallpaperHeartbeat: Codable, Equatable {
    var timestamp: Date
    var activeChoiceID: String?
    /// Every choice currently on some display — the single field above keeps
    /// one arbitrary member for readers that predate multi-display support.
    var activeChoiceIDs: [String]?
    /// False when the appex's private-API layout check failed on this OS —
    /// the app shows the "system incompatible" state instead of guessing.
    var runtimeHealthy: Bool
    /// The OS build the verdict above was reached on. A layout check is only
    /// meaningful for the build that ran it; after an OS update a stale
    /// "unhealthy" from the old build must not keep the feature locked out.
    var osVersion: String?

    init(timestamp: Date, activeChoiceID: String?, activeChoiceIDs: [String]? = nil,
         runtimeHealthy: Bool = true, osVersion: String? = nil) {
        self.timestamp = timestamp
        self.activeChoiceID = activeChoiceID
        self.activeChoiceIDs = activeChoiceIDs
        self.runtimeHealthy = runtimeHealthy
        self.osVersion = osVersion
    }

    private enum CodingKeys: String, CodingKey {
        case timestamp, activeChoiceID, activeChoiceIDs, runtimeHealthy, osVersion
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        timestamp = try c.decode(Date.self, forKey: .timestamp)
        activeChoiceID = try c.decodeIfPresent(String.self, forKey: .activeChoiceID)
        activeChoiceIDs = try c.decodeIfPresent([String].self, forKey: .activeChoiceIDs)
        runtimeHealthy = try c.decodeIfPresent(Bool.self, forKey: .runtimeHealthy) ?? true
        osVersion = try c.decodeIfPresent(String.self, forKey: .osVersion)
    }

    /// Is `itemID` on some display according to this heartbeat?
    func showsChoice(_ itemID: String) -> Bool {
        if let activeChoiceIDs { return activeChoiceIDs.contains(itemID) }
        return activeChoiceID == itemID
    }

    /// Version plus build: beta seeds keep the same x.y.z across weekly builds,
    /// and a layout verdict is only valid for the exact build that produced it.
    static func currentOSVersion() -> String {
        let v = ProcessInfo.processInfo.operatingSystemVersion
        var size = 0
        sysctlbyname("kern.osversion", nil, &size, nil, 0)
        var buffer = [UInt8](repeating: 0, count: max(size, 1))
        let build: String
        if size > 0, sysctlbyname("kern.osversion", &buffer, &size, nil, 0) == 0 {
            build = String(decoding: buffer.prefix(while: { $0 != 0 }), as: UTF8.self)
        } else {
            build = ""
        }
        return "\(v.majorVersion).\(v.minorVersion).\(v.patchVersion)-\(build)"
    }
}

/// Both sides must encode with identical settings or the appex silently reads
/// an empty library — keep the coders here rather than at each call site.
enum SystemWallpaperCoding {
    static var encoder: JSONEncoder { JSONEncoder() }
    static var decoder: JSONDecoder { JSONDecoder() }
}

enum SystemWallpaperPaths {
    static let darwinLibraryChangedNote = "com.loomscreen.wallpaper.libraryChanged"

    /// Real (non-redirected) home. Inside a sandbox, `NSHomeDirectory()` and
    /// `homeDirectoryForCurrentUser` point at the *container*, so the app and
    /// the appex would each resolve a different directory (plan §2, tested).
    static var realHomeDirectory: URL {
        guard let pw = getpwuid(getuid()), let dir = pw.pointee.pw_dir else {
            return FileManager.default.homeDirectoryForCurrentUser
        }
        return URL(fileURLWithPath: String(cString: dir), isDirectory: true)
    }

    /// Shared root inside the given host app's container.
    static func sharedRoot(hostBundleID: String) -> URL {
        realHomeDirectory
            .appendingPathComponent("Library/Containers/\(hostBundleID)/Data/Library/Application Support/Loomscreen/SystemWallpaper", isDirectory: true)
    }

    static func manifestURL(hostBundleID: String) -> URL {
        sharedRoot(hostBundleID: hostBundleID).appendingPathComponent("manifest.json")
    }

    static func heartbeatURL(hostBundleID: String) -> URL {
        sharedRoot(hostBundleID: hostBundleID).appendingPathComponent("heartbeat.json")
    }

    static func videosDirectory(hostBundleID: String) -> URL {
        sharedRoot(hostBundleID: hostBundleID).appendingPathComponent("Videos", isDirectory: true)
    }
}

/// Library mutations that both sides perform: the app when the user removes a
/// video in Loomscreen, and the extension when macOS's own wallpaper panel
/// asks for a removal. One implementation so the two can never disagree about
/// what "removed" leaves behind.
enum SystemWallpaperLibrary {
    /// Removes `id`: persists the shrunk manifest first (via `persist`), and
    /// only then deletes the files. That order means a failed persist leaves a
    /// still-consistent library, and a failed delete leaves an orphan the
    /// sweep below reclaims — never a manifest entry pointing at nothing.
    /// Returns the new manifest, or nil when the id was not present.
    static func remove(
        id: String,
        from manifest: SystemWallpaperManifest,
        videosDirectory: URL,
        persist: (SystemWallpaperManifest) throws -> Void
    ) rethrows -> SystemWallpaperManifest? {
        guard let item = manifest.items.first(where: { $0.id == id }) else { return nil }
        var updated = manifest
        updated.items.removeAll { $0.id == id }
        try persist(updated)
        let manager = FileManager.default
        try? manager.removeItem(at: videosDirectory.appendingPathComponent(item.fileName))
        if let thumbnailFileName = item.thumbnailFileName {
            try? manager.removeItem(at: videosDirectory.appendingPathComponent(thumbnailFileName))
        }
        return updated
    }

    /// Files in Videos/ that no manifest entry references — left behind by a
    /// crash between copy and manifest write, or by a lost manifest update.
    /// The age guard keeps a publish-in-progress (copied, not yet listed)
    /// safe from a concurrent sweep.
    static func sweepOrphans(
        manifest: SystemWallpaperManifest,
        videosDirectory: URL,
        olderThan age: TimeInterval = 3600,
        now: Date = Date()
    ) {
        var referenced = Set<String>()
        for item in manifest.items {
            referenced.insert(item.fileName)
            if let thumb = item.thumbnailFileName { referenced.insert(thumb) }
        }
        let manager = FileManager.default
        let files = (try? manager.contentsOfDirectory(
            at: videosDirectory,
            includingPropertiesForKeys: [.contentModificationDateKey]
        )) ?? []
        for file in files where !referenced.contains(file.lastPathComponent) {
            let modified = (try? file.resourceValues(forKeys: [.contentModificationDateKey])
                .contentModificationDate) ?? now
            guard now.timeIntervalSince(modified) > age else { continue }
            try? manager.removeItem(at: file)
        }
    }
}

/// Serializes the read–modify–write both processes perform on the manifest.
/// Atomic writes alone only prevent torn JSON — without this, app and appex
/// mutating concurrently means the later writer silently drops the earlier
/// writer's change (lost update, not "no-op loser").
enum SystemWallpaperLock {
    static func withExclusiveLock<T>(root: URL, _ body: () throws -> T) throws -> T {
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        let lockURL = root.appendingPathComponent("manifest.lock")
        let fd = open(lockURL.path, O_CREAT | O_WRONLY, 0o644)
        guard fd >= 0 else {
            // Can't lock — better to run unserialized than to drop the mutation.
            return try body()
        }
        defer { close(fd) }
        // A signal can interrupt the blocking flock (EINTR); giving up there
        // would silently run the mutation unserialized, which is the exact
        // lost update this lock exists to prevent.
        var locked = false
        repeat {
            if flock(fd, LOCK_EX) == 0 {
                locked = true
                break
            }
        } while errno == EINTR
        defer { if locked { flock(fd, LOCK_UN) } }
        return try body()
    }
}
